// Pure pediatric blood-pressure interpretation over the baked AAP 2017 normative
// tables (lib/bp-percentiles.json, generated by scripts/gen-bp-percentiles.ts) —
// issue #150.
//
// Adult fixed thresholds mis-classify a child's blood pressure: what is "normal"
// depends on AGE, SEX, and the child's HEIGHT PERCENTILE. This module turns a
// measured systolic/diastolic reading (mmHg) plus the child's sex, age (whole
// years), and height percentile into:
//   • PERCENTILE — where the reading falls among same-age, same-sex, same-height
//     peers (interpolated across the seven height-percentile columns), clamped at
//     the 50th/95th table edges.
//   • CATEGORY — the AAP 2017 class: Normal / Elevated / Stage 1 / Stage 2.
//     For ages 1-12 the class is percentile-based (with the guideline's static
//     120/80, 130/80, 140/90 caps, "whichever is lower"); from age 13 the AAP
//     adopts the static adolescent/adult thresholds, so the class is those.
//
// DB-free and pure so it's unit-tested in lib/__tests__/bp-percentiles.test.ts.
// Sex/age come from profile_settings and height percentile from the growth-chart
// data (lib/growth.ts) at the call site. When sex or age is unset, or the subject
// is outside the pediatric 1-17 window, the entry points return null so the surface
// falls back to the adult range display — the same age/sex gating the lab age-band
// and fitness-norm surfaces use. INFORMATIONAL, not medical advice.

import type { Sex } from "@/lib/types";
import data from "@/lib/bp-percentiles.json";

export type BpComponent = "systolic" | "diastolic";
export type BpCategory = "normal" | "elevated" | "stage1" | "stage2";

interface BpRow {
  age: number;
  pct: number;
  sbp: number[];
  dbp: number[];
}
interface BpDataset {
  source: string;
  heightPercentiles: number[];
  bpPercentiles: number[];
  minAge: number;
  maxAge: number;
  sexes: { male: BpRow[]; female: BpRow[] };
}
const DATA = data as unknown as BpDataset;

export const BP_PERCENTILE_SOURCE = DATA.source;
// AAP switches from percentile-based to static adult-style thresholds at 13 y.
export const ADULT_BP_AGE = 13;

// The canonical biomarker names carrying pediatric BP interpretation. Must match
// the canonical_biomarkers rows / vitals-input canonical names byte-for-byte.
const MARKER_COMPONENT: Record<string, BpComponent> = {
  "Blood Pressure Systolic": "systolic",
  "Blood Pressure Diastolic": "diastolic",
};

// Which BP component a canonical biomarker name is, or null when it isn't a BP
// marker. Drives whether a detail surface shows the pediatric BP card.
export function bpComponentFor(name: string): BpComponent | null {
  return MARKER_COMPONENT[name] ?? null;
}

// The three threshold values (at the 50th/90th/95th BP percentiles) for one
// component at an exact height percentile — the row vectors interpolated across the
// height-percentile columns.
export interface BpThresholds {
  p50: number;
  p90: number;
  p95: number;
}

// Linear interpolation of a 7-long value vector at a height percentile, over the
// dataset's height-percentile anchors; clamped to the first/last column outside
// [5, 95]. Pure and order-independent (anchors ascending).
function interpAtHeight(values: number[], heightPct: number): number {
  const anchors = DATA.heightPercentiles;
  if (heightPct <= anchors[0]) return values[0];
  const n = anchors.length;
  if (heightPct >= anchors[n - 1]) return values[n - 1];
  for (let i = 1; i < n; i++) {
    if (heightPct <= anchors[i]) {
      const span = anchors[i] - anchors[i - 1];
      const t = span === 0 ? 0 : (heightPct - anchors[i - 1]) / span;
      return values[i - 1] + t * (values[i] - values[i - 1]);
    }
  }
  return values[n - 1];
}

// The BP thresholds (mmHg) for a component at a sex/age/height percentile, or null
// when age is outside the table (1-17) or sex is unset. Age is used as whole years
// (clamped into [1,17]); height percentile is clamped into the table's [5,95].
export function bpThresholds(
  component: BpComponent,
  sex: Sex | null | undefined,
  ageYears: number | null | undefined,
  heightPct: number
): BpThresholds | null {
  if (sex !== "male" && sex !== "female") return null;
  if (ageYears == null || !Number.isFinite(ageYears)) return null;
  const age = Math.min(
    DATA.maxAge,
    Math.max(DATA.minAge, Math.floor(ageYears))
  );
  const rows = DATA.sexes[sex].filter((r) => r.age === age);
  if (rows.length === 0) return null;
  const pick = (pct: number) => rows.find((r) => r.pct === pct);
  const r50 = pick(50);
  const r90 = pick(90);
  const r95 = pick(95);
  if (!r50 || !r90 || !r95) return null;
  const key = component === "systolic" ? "sbp" : "dbp";
  return {
    p50: interpAtHeight(r50[key], heightPct),
    p90: interpAtHeight(r90[key], heightPct),
    p95: interpAtHeight(r95[key], heightPct),
  };
}

export type Clamp = "low" | "high" | null;
export interface BpPercentileResult {
  percentile: number; // rounded 50..95 (clamped at the table edges)
  clamped: Clamp; // "low" = at/under the 50th, "high" = at/over the 95th
}

// Place a measured value on the (BP percentile → mmHg) curve [50th, 90th, 95th] at
// the child's height. Interpolates within [50,90] and [90,95]; clamps under the
// 50th ("low") and over the 95th ("high"). Monotonic thresholds assumed.
export function bpPercentile(
  value: number,
  thr: BpThresholds
): BpPercentileResult {
  if (value <= thr.p50) return { percentile: 50, clamped: "low" };
  if (value >= thr.p95) return { percentile: 95, clamped: "high" };
  if (value <= thr.p90) {
    const span = thr.p90 - thr.p50;
    const t = span === 0 ? 0 : (value - thr.p50) / span;
    return { percentile: Math.round(50 + t * 40), clamped: null };
  }
  const span = thr.p95 - thr.p90;
  const t = span === 0 ? 0 : (value - thr.p90) / span;
  return { percentile: Math.round(90 + t * 5), clamped: null };
}

// Per-component static caps (mmHg) the AAP applies "whichever is lower" against the
// percentile thresholds (ages 1-12), and the adolescent/adult thresholds (age ≥13).
const STATIC = {
  systolic: { elevated: 120, stage1: 130, stage2: 140 },
  diastolic: { elevated: 80, stage1: 80, stage2: 90 },
} as const;

// Classify one BP component into an AAP 2017 category. For age ≥13 the static
// adolescent/adult thresholds apply (diastolic has no "elevated" band — <80 normal,
// 80-89 Stage 1, ≥90 Stage 2). For ages 1-12 the percentile thresholds apply,
// each capped by the static value ("whichever is lower").
export function bpComponentCategory(
  component: BpComponent,
  value: number,
  ageYears: number,
  thr: BpThresholds
): BpCategory {
  const s = STATIC[component];
  if (ageYears >= ADULT_BP_AGE) {
    if (value >= s.stage2) return "stage2";
    if (value >= s.stage1) return "stage1";
    if (component === "systolic" && value >= s.elevated) return "elevated";
    return "normal";
  }
  const elevatedT = Math.min(thr.p90, s.elevated);
  const stage1T = Math.min(thr.p95, s.stage1);
  const stage2T = Math.min(thr.p95 + 12, s.stage2);
  if (value >= stage2T) return "stage2";
  if (value >= stage1T) return "stage1";
  if (value >= elevatedT) return "elevated";
  return "normal";
}

export interface PediatricBpContext {
  component: BpComponent;
  value: number;
  percentile: number;
  clamped: Clamp;
  category: BpCategory;
  heightPercentile: number;
  heightAssumed: boolean; // true when no tracked height → assumed 50th percentile
  adultRegime: boolean; // true at age ≥13 (static thresholds, not percentile-based)
  source: string;
}

// The full pediatric BP context a surface renders for ONE component reading, or
// null when it doesn't apply (sex/age unset, or age outside the 1-17 pediatric
// window). Height percentile is optional: when the child has no tracked height it
// defaults to the 50th percentile (flagged via `heightAssumed`) so the category
// still computes rather than silently falling back to the adult thresholds.
export function pediatricBpContext(
  component: BpComponent,
  value: number | null | undefined,
  opts: {
    sex: Sex | null | undefined;
    ageYears: number | null | undefined;
    heightPercentile?: number | null;
  }
): PediatricBpContext | null {
  const { sex, ageYears } = opts;
  if (sex !== "male" && sex !== "female") return null;
  if (value == null || !Number.isFinite(value)) return null;
  if (ageYears == null || !Number.isFinite(ageYears)) return null;
  if (ageYears < DATA.minAge || ageYears > DATA.maxAge) return null;
  const heightAssumed =
    opts.heightPercentile == null || !Number.isFinite(opts.heightPercentile);
  const heightPct = heightAssumed ? 50 : (opts.heightPercentile as number);
  const thr = bpThresholds(component, sex, ageYears, heightPct);
  if (!thr) return null;
  const p = bpPercentile(value, thr);
  return {
    component,
    value,
    percentile: p.percentile,
    clamped: p.clamped,
    category: bpComponentCategory(component, value, Math.floor(ageYears), thr),
    heightPercentile: heightPct,
    heightAssumed,
    adultRegime: Math.floor(ageYears) >= ADULT_BP_AGE,
    source: DATA.source,
  };
}

// The worse of two categories — for a combined systolic+diastolic classification of
// a single BP reading (the AAP overall class is the higher of the two components).
const RANK: Record<BpCategory, number> = {
  normal: 0,
  elevated: 1,
  stage1: 2,
  stage2: 3,
};
export function worseBpCategory(a: BpCategory, b: BpCategory): BpCategory {
  return RANK[a] >= RANK[b] ? a : b;
}

// The overall AAP class of a full BP reading (both components), or null when it
// doesn't apply. The class is the worse of the systolic and diastolic components.
export function pediatricBpOverall(
  systolic: number | null | undefined,
  diastolic: number | null | undefined,
  opts: {
    sex: Sex | null | undefined;
    ageYears: number | null | undefined;
    heightPercentile?: number | null;
  }
): {
  category: BpCategory;
  systolic: PediatricBpContext;
  diastolic: PediatricBpContext;
} | null {
  const s = pediatricBpContext("systolic", systolic, opts);
  const d = pediatricBpContext("diastolic", diastolic, opts);
  if (!s || !d) return null;
  return {
    category: worseBpCategory(s.category, d.category),
    systolic: s,
    diastolic: d,
  };
}

// ── Display helpers ─────────────────────────────────────────────────────────────

export const BP_CATEGORY_META: Record<
  BpCategory,
  { label: string; chip: string }
> = {
  normal: {
    label: "Normal for age",
    chip: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
  },
  elevated: {
    label: "Elevated",
    chip: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
  },
  stage1: {
    label: "Stage 1 hypertension",
    chip: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300",
  },
  stage2: {
    label: "Stage 2 hypertension",
    chip: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300",
  },
};

// "50th"/"92nd"/"95th" — ordinal suffix for the percentile copy.
export function ordinal(n: number): string {
  const abs = Math.abs(Math.round(n));
  const mod100 = abs % 100;
  if (mod100 >= 11 && mod100 <= 13) return `${abs}th`;
  switch (abs % 10) {
    case 1:
      return `${abs}st`;
    case 2:
      return `${abs}nd`;
    case 3:
      return `${abs}rd`;
    default:
      return `${abs}th`;
  }
}

// Human phrase for a BP percentile: "92nd percentile", "≥ 95th percentile"
// (clamped high), "≤ 50th percentile" (clamped low).
export function formatBpPercentile(ctx: PediatricBpContext): string {
  if (ctx.clamped === "high") return `≥ ${ordinal(ctx.percentile)} percentile`;
  if (ctx.clamped === "low") return `≤ ${ordinal(ctx.percentile)} percentile`;
  return `${ordinal(ctx.percentile)} percentile`;
}
