// Pure calorie ESTIMATOR for manually-logged activities (issue #151).
//
// Imported activities carry device-measured energy; manual ones don't. This module
// turns the baked MET dataset (lib/mets.json, generated by scripts/gen-mets.ts from
// the PUBLIC Compendium of Physical Activities) plus a bodyweight and a duration
// into an ESTIMATED calorie burn:
//
//     kcal = METs × weight(kg) × hours
//
// Everything here is an ESTIMATE — a population-average number, never a measurement.
// It is stored and displayed DISTINCTLY from device-measured calories and is only
// ever produced for MANUAL activities (source == null); an imported row's device
// energy is never shadowed by an estimate (the manual-vs-integration source
// separation the rest of the app follows). No DB, no network — importable by the
// activity form (client), the query/recap layer (server), and the unit tests alike.

import metsData from "./mets.json";
import type { ActivityComponent, ActivityType } from "./types";

export type MetTier = "easy" | "moderate" | "hard";

interface MetTiers {
  easy: number;
  moderate: number;
  hard: number;
}
interface MetsDataset {
  defaultTier: MetTier;
  activities: Record<string, MetTiers>;
  typeDefaults: Record<ActivityType, MetTiers>;
}

const DATA = metsData as unknown as MetsDataset;

// Case-insensitive activity-name → MET-tiers lookup, built once at module load.
const BY_LOWER_NAME = new Map<string, MetTiers>(
  Object.entries(DATA.activities).map(([k, v]) => [k.toLowerCase(), v])
);

// Map a stored intensity string to a MET tier. The activity form stores
// easy | moderate | hard (lib/activity-form-model.INTENSITIES); anything else
// (null, "", a legacy label) resolves to the dataset's default tier (moderate) so a
// no-intensity activity still gets a sensible mid estimate.
export function intensityToTier(intensity: string | null | undefined): MetTier {
  const v = (intensity ?? "").trim().toLowerCase();
  if (v === "easy" || v === "moderate" || v === "hard") return v;
  return DATA.defaultTier;
}

// Resolve a MET value for an activity NAME of a given TYPE at an intensity. A name
// in the catalog dataset uses its own tiered value; anything else (a user-coined
// cardio/sport name, or any strength lift — strength is never enumerated by name)
// falls back to the per-TYPE default. Returns null only if the type has no default
// (unreachable for the three known activity types).
export function metsForActivity(
  name: string,
  type: ActivityType,
  intensity?: string | null
): number | null {
  const tier = intensityToTier(intensity);
  const named = BY_LOWER_NAME.get(name.trim().toLowerCase());
  if (named) return named[tier];
  const def = DATA.typeDefaults[type];
  return def ? def[tier] : null;
}

// kcal = METs × weight(kg) × hours, rounded to a whole calorie. Returns null when
// ANY input is missing or non-positive — most importantly a MISSING BODYWEIGHT
// yields null, so the caller shows no estimate rather than a fabricated 0 (the
// missing-bodyweight fallback the acceptance calls out).
export function estimateKcal(
  mets: number | null,
  weightKg: number | null,
  durationMin: number | null
): number | null {
  if (mets == null || mets <= 0) return null;
  if (weightKg == null || weightKg <= 0) return null;
  if (durationMin == null || durationMin <= 0) return null;
  return Math.round(mets * weightKg * (durationMin / 60));
}

export interface DatedWeight {
  date: string; // YYYY-MM-DD
  weightKg: number;
}

// Whole-day distance between two YYYY-MM-DD strings (unsigned), via UTC midnight so
// DST never shifts it. Used to pick the nearest weigh-in.
function absDayDiff(a: string, b: string): number {
  const da = Date.parse(`${a}T00:00:00Z`);
  const db = Date.parse(`${b}T00:00:00Z`);
  if (Number.isNaN(da) || Number.isNaN(db)) return Number.POSITIVE_INFINITY;
  return Math.abs(Math.round((da - db) / 86_400_000));
}

// The profile's NEAREST-IN-TIME bodyweight to `date`: the weigh-in whose date is
// closest (either side), ties broken toward the MORE RECENT reading. Returns null
// when there are no usable weights — the missing-bodyweight case (estimateKcal then
// returns null too). `weights` need not be sorted.
export function nearestBodyweightKg(
  weights: DatedWeight[],
  date: string
): number | null {
  let best: DatedWeight | null = null;
  let bestDiff = Number.POSITIVE_INFINITY;
  for (const w of weights) {
    if (w.weightKg == null || !(w.weightKg > 0)) continue;
    const diff = absDayDiff(w.date, date);
    if (
      diff < bestDiff ||
      (diff === bestDiff && (best == null || w.date > best.date))
    ) {
      best = w;
      bestDiff = diff;
    }
  }
  return best ? best.weightKg : null;
}

function parseComponents(json: string | null | undefined): ActivityComponent[] {
  if (!json) return [];
  try {
    const arr = JSON.parse(json);
    return Array.isArray(arr) ? (arr as ActivityComponent[]) : [];
  } catch {
    return [];
  }
}

// The activity fields the estimate needs. A subset of Activity so the form's
// in-progress draft (which isn't a full stored row) can be estimated too.
export interface EstimableActivity {
  type: ActivityType;
  title: string;
  intensity: string | null;
  duration_min: number | null;
  components: string | null; // JSON ActivityComponent[]
  source?: string | null;
}

// Only MANUAL activities (source == null) get an estimate; an imported row already
// carries device energy and must never be shadowed by one.
export function isEstimable(a: { source?: string | null }): boolean {
  return a.source == null;
}

// The ESTIMATED calorie burn for one activity given a bodyweight. When the activity
// has multi-part components WITH their own durations, each part is estimated on its
// own MET (name + type) and duration and summed (a bike+run brick burns each leg at
// its own rate). Otherwise the activity's overall duration is scored at the primary
// component's MET (first named part, else the activity title + type). Returns null
// when there's no bodyweight or no usable duration.
export function estimateActivityKcal(
  a: EstimableActivity,
  weightKg: number | null
): number | null {
  if (weightKg == null || weightKg <= 0) return null;
  const comps = parseComponents(a.components);
  const withDur = comps.filter(
    (c) => c.duration_min != null && c.duration_min > 0
  );
  if (withDur.length > 0) {
    let total = 0;
    let any = false;
    for (const c of withDur) {
      const mets = metsForActivity(c.name, c.type, a.intensity);
      const kcal = estimateKcal(mets, weightKg, c.duration_min);
      if (kcal != null) {
        total += kcal;
        any = true;
      }
    }
    return any ? total : null;
  }
  const primary = comps[0];
  const name = primary?.name ?? a.title;
  const type = primary?.type ?? a.type;
  const mets = metsForActivity(name, type, a.intensity);
  return estimateKcal(mets, weightKg, a.duration_min);
}

// A stored activity that may carry a saved estimate/override in est_calories.
export interface StoredActivityForEstimate extends EstimableActivity {
  // The value the form saved: the auto-estimate at save time, or the user's manual
  // override. NULL for legacy/seed rows the form never touched.
  est_calories?: number | null;
}

// The estimate to DISPLAY for a stored activity: the saved est_calories (override
// or the form's snapshot) when present, else a freshly computed estimate from the
// MET dataset + the given bodyweight. Null for non-manual rows and when nothing can
// be computed. This is the single "what estimate does this activity show" decision
// used by every surface (per-activity chip, recap total, trends), so they can't
// disagree.
export function activityEstimateKcal(
  a: StoredActivityForEstimate,
  weightKg: number | null
): number | null {
  if (!isEstimable(a)) return null;
  if (a.est_calories != null && a.est_calories > 0)
    return Math.round(a.est_calories);
  return estimateActivityKcal(a, weightKg);
}

// Total estimated calories over a set of dated activities, each scored against the
// bodyweight nearest its own date. Used by the weekly recap / trends. Non-manual
// rows contribute nothing.
export function totalEstimatedKcal(
  activities: (StoredActivityForEstimate & { date: string })[],
  weights: DatedWeight[]
): number {
  let total = 0;
  for (const a of activities) {
    const bw = nearestBodyweightKg(weights, a.date);
    const kcal = activityEstimateKcal(a, bw);
    if (kcal != null) total += kcal;
  }
  return total;
}

// Compact display string for an estimated calorie value, e.g. "≈ 320 kcal". The "≈"
// marks it as an estimate wherever it renders. Returns null (no chip) for a null.
export function formatEstimatedKcal(kcal: number | null): string | null {
  if (kcal == null || kcal <= 0) return null;
  return `≈ ${Math.round(kcal).toLocaleString("en-US")} kcal`;
}
