// Pure supplement stack-total UL checker (issue #148) — the supplement-side twin
// of drug-interaction checking. Given a profile's active supplement/medication
// stack (each item's scheduled dose amounts) plus its age/sex, it sums the daily
// intake PER NUTRIENT and flags any nutrient whose stack total exceeds the NIH
// Tolerable Upper Intake Level (UL). No DB, no network — the DB gather lives in
// lib/queries/intake.ts (getDietaryLimitWarnings), which calls the pure functions
// here so the intake surface warning row and the dismissible Upcoming finding are
// formatters over ONE computation (AGENTS.md "one question, one computation").
//
// The reference values (UL/RDA by age/sex, the supplemental-vs-total `basis`, the
// IU factors) come from the committed lib/dri.json, generated by scripts/gen-dri.ts
// from PUBLIC-DOMAIN NIH DRI tables. The supplement-name → nutrient vocabulary
// lives HERE (NAME_MATCHERS) — the app's supplement catalog is what we recognize;
// the dataset is the reference figures. lib/__tests__/dri-dataset.test.ts pins that
// every nutrient a matcher references exists in the dataset (anti-drift), and that
// the committed JSON is a fixed point of the generator.
//
// CRITICAL — supplemental vs total basis: a supplemental-basis UL (magnesium,
// niacin, folic acid, supplemental vitamin E) is defined over supplement intake
// alone, so "your stack totals X, the UL is Y" is exact. A total-basis UL (vitamin
// A, D, calcium, iron, …) is defined over intake from ALL sources; the app only
// knows supplements, so exceeding a total UL from supplements alone is a definite
// exceedance (food only adds more) but the copy must say so. Both surface a warning
// when the supplemental sum exceeds the UL — the `basis` flag drives the WORDING.
// Everything here is INFORMATIONAL, never prescriptive: the copy is "discuss with
// your clinician", never "stop taking X".

import type { Sex } from "./types";
import type { ConditionInput } from "./condition-codes";
import { conditionsContraindicatingNutrient } from "./condition-nutrient";
import { DRI_NUTRIENTS } from "./datasets/dri";

export interface DriBand {
  min_age: number;
  max_age: number | null;
  sex?: "male" | "female";
  ul: number | null;
  rda: number | null;
}

export interface DriNutrient {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  iu?: number | null;
  note?: string | null;
  bands: DriBand[];
}

const NUTRIENTS = DRI_NUTRIENTS;
const BY_KEY = new Map(NUTRIENTS.map((n) => [n.key, n]));

// When the profile's age is unknown, score against a default ADULT age: adult ULs
// are the most permissive band for every nutrient here, so an unknown-age adult is
// never OVER-flagged against a stricter child band it may not belong to.
export const DEFAULT_ADULT_AGE = 30;

// IntakeItem/medication NAME → nutrient key. Ordered; the first matching pattern
// wins. Patterns are matched case-insensitively against the item name. This is the
// app's recognized vocabulary (the supplement catalog): a name that matches nothing
// (a multivitamin, a herb, a protein) contributes to no nutrient total — a
// documented fallback, pinned by the dataset test to only ever reference real keys.
// Every key here MUST exist in dri.json.
const NAME_MATCHERS: { pattern: RegExp; key: string }[] = [
  // Magnesium carries the shelf spellings this catalog actually meets (#2934):
  //   * `magnesia` — "Milk of Magnesia" is a real magnesium product and the word
  //     names the mineral outright; nothing else in the catalog contains it.
  //   * `Mag <form>` — "Mag Threonate" is a common front-of-bottle abbreviation.
  //     The FORM WORD is the evidence, not the abbreviation: a bare /\bmag\b/i
  //     would count "Mag 07" and any other product that shortens the word, so the
  //     match requires a magnesium salt to follow. That leaves a genuine
  //     under-count on an abbreviation with no form word, which is the direction
  //     this may fail in — it never invents a dose.
  {
    pattern:
      /magnesium|\bmagnesia\b|\bmag\b[\s-]+(?:l[\s-]?)?(?:threonate|glycinate|citrate|malate|taurate|oxide|hydroxide|chloride|sulfate|sulphate|carbonate|lactate|orotate|aspartate)/i,
    key: "magnesium",
  },
  { pattern: /\bzinc\b/i, key: "zinc" },
  { pattern: /\bcalcium\b/i, key: "calcium" },
  { pattern: /\biron\b/i, key: "iron" },
  { pattern: /\bselenium\b/i, key: "selenium" },
  { pattern: /\bcopper\b/i, key: "copper" },
  { pattern: /\bmanganese\b/i, key: "manganese" },
  { pattern: /\biodine\b/i, key: "iodine" },
  { pattern: /\bmolybdenum\b/i, key: "molybdenum" },
  { pattern: /\bboron\b/i, key: "boron" },
  { pattern: /vitamin\s*b6|pyridoxine/i, key: "vitamin_b6" },
  { pattern: /niacin|nicotinic\s*acid|niacinamide/i, key: "niacin" },
  { pattern: /\bfolate\b|folic\s*acid/i, key: "folate" },
  { pattern: /vitamin\s*a\b/i, key: "vitamin_a" },
  { pattern: /vitamin\s*c\b/i, key: "vitamin_c" },
  { pattern: /vitamin\s*d/i, key: "vitamin_d" },
  { pattern: /vitamin\s*e\b/i, key: "vitamin_e" },
];

// Every nutrient key the matchers can resolve — exported so the dataset test can
// assert each resolves in dri.json (anti-drift).
export const MATCHER_KEYS: string[] = [
  ...new Set(NAME_MATCHERS.map((m) => m.key)),
];

// Names that MENTION a nutrient without being a dose of it (#2934). `Magnesium
// Stearate` is the proven case: one of the most common tablet excipients, a flow
// agent present in trace amounts, which `/magnesium/i` counted as a magnesium dose
// and summed toward the upper limit.
//
// Each entry is REDACTED from the name before the matchers run, rather than vetoing
// the whole name. A veto would be the wrong tool: an excipient can be named
// ALONGSIDE the real dose ("Magnesium Citrate (with magnesium stearate)"), and
// that product does dose magnesium. Redaction removes only the mention that is not
// a dose and lets whatever remains speak.
//
// This is deliberately a list of NAMED COMPOUNDS, not of the bare words `stearate`
// or `silicate`: the mineral has to be the one being excused, so the excuse cannot
// spread to a form the catalog might legitimately dose.
//
// AND NAMING A COMPOUND IS NOT ENOUGH — it has to be one that is never the dose.
// Magnesium SILICATE is talc, an anticaking agent. Magnesium TRISILICATE differs by
// three letters and by everything else: it is a licensed antacid active ingredient
// (BP/USP monograph, 250–500 mg tablets), and excusing it silenced a 2000 mg/day
// stack this module had correctly warned on — a stack going quiet is the one
// direction it may never move, and antacid-driven hypermagnesemia in renal
// impairment is precisely the CKD case `ulConditionCaveat` exists for. So
// `silicate` is matched exactly, and `trisilicate` resolves like the dose it is.
const EXCIPIENT_MENTIONS: RegExp[] = [
  /\b(?:magnesium|calcium|zinc|sodium|potassium)[\s-]+stearates?\b/gi,
  /\b(?:magnesium|calcium)[\s-]+silicate\b/gi,
];

// Resolve a supplement/medication name to a nutrient key, or null when it maps to
// no UL-bearing nutrient (the common case for herbs, proteins, multivitamins) or
// when the only mention of one was an excipient.
//
// ONE VOCABULARY, TWO READERS. Both the UL check (a risk number) and the RDA
// adequacy note (a reassurance number) resolve names through here, and recognition
// moves them in OPPOSITE directions: counting an excipient inflates the risk number
// AND the reassurance number, so ceasing to count it deflates both. That is the
// honest outcome in each case — an excipient is not exposure and it is not intake —
// but it is the reason recognition is decided once, here, instead of per reader.
export function resolveNutrientKey(name: string): string | null {
  const evidence = EXCIPIENT_MENTIONS.reduce(
    (s, re) => s.replace(re, " "),
    name
  );
  for (const m of NAME_MATCHERS) if (m.pattern.test(evidence)) return m.key;
  return null;
}

export function nutrientByKey(key: string): DriNutrient | undefined {
  return BY_KEY.get(key);
}

// ---- Unit parsing + conversion (pure, tested) ----

export type DoseUnit = "mg" | "mcg" | "g" | "iu";

// The units an INGREDIENT row may be stored in (issue #2856): canonical mass, or an
// International Unit that only a nutrient can convert. Grams are folded to mg at the
// write boundary, so `g` is deliberately absent here.
export type IngredientUnit = "mg" | "mcg" | "iu";

export interface ParsedQuantity {
  value: number;
  unit: DoseUnit;
}

// Parse the leading quantity out of a dose amount string ("400 mg", "5000 IU",
// "200 mcg", "5 g", "1.5 g"). Returns the FIRST number+unit found — so a combo
// amount like "2000 IU / 100 mcg" (Vitamin D3 + K2) yields the leading nutrient's
// 2000 IU. A non-quantitative amount ("1 capsule", "1 scoop", null) returns null:
// its nutrient content is unknown, so it's excluded (documented fallback). "mcg",
// "µg" and "ug" all normalize to mcg; unit match is case-insensitive.
export function parseQuantity(amount: string | null): ParsedQuantity | null {
  if (!amount) return null;
  const m = amount.match(/(\d+(?:\.\d+)?)\s*(mcg|µg|ug|mg|g|iu)\b/i);
  if (!m) return null;
  const value = Number(m[1]);
  if (!Number.isFinite(value)) return null;
  let u = m[2].toLowerCase();
  if (u === "µg" || u === "ug") u = "mcg";
  return { value, unit: u as DoseUnit };
}

// How many LABEL UNITS (capsules, tablets, scoops) one dose row is (issue #2856).
// Ingredient amounts are stated per single dose unit, so a blend taken two capsules
// at a time contributes twice each ingredient — a question a name-only stack never
// had to ask, because a name-derived amount IS the dose.
//
// A dose row that states a MASS or an IU quantity ("400 mg", "5000 IU") counts as ONE
// unit: that string is the item's strength, not a count of label units, and reading
// "400 mg" as four hundred capsules would multiply a blend's zinc by four hundred on
// the most safety-critical number this app computes. Otherwise the leading number is
// the count ("2 capsules" → 2, "1 cap" → 1), and anything without one — including an
// empty amount — is one unit, the same assumption the dose strips already display.
//
// A fractional label ("1/2 tablet") reads as 1 rather than 0.5: the leading number is
// taken as written. That errs HIGH, the direction this module errs in everywhere (see
// the conservative-direction rule below) — a small over-count on a half dose is
// recoverable, silently under-counting a real exceedance is not.
export function doseUnitCount(amount: string | null): number {
  if (!amount || !amount.trim()) return 1;
  if (parseQuantity(amount)) return 1;
  const m = amount.match(/^\s*(\d+(?:\.\d+)?)/);
  if (!m) return 1;
  const n = Number(m[1]);
  return Number.isFinite(n) && n > 0 ? n : 1;
}

// Milligrams-per-unit for the mass units, used to convert any mass dose into a
// nutrient's canonical unit (mg or mcg).
const MASS_MG: Record<"mg" | "mcg" | "g", number> = {
  g: 1000,
  mg: 1,
  mcg: 0.001,
};

// Convert a parsed dose quantity into the nutrient's canonical unit, or null when
// it can't be converted (an IU dose for a nutrient with no IU factor). Mass units
// convert generically via milligrams; an IU dose uses the nutrient's `iu` factor
// (canonical units per IU, e.g. vitamin D 0.025 mcg/IU).
export function toNutrientUnit(
  q: ParsedQuantity,
  nutrient: DriNutrient
): number | null {
  if (q.unit === "iu") {
    if (nutrient.iu == null) return null;
    return q.value * nutrient.iu;
  }
  // Mass → canonical mg, then mg → canonical unit.
  const mg = q.value * MASS_MG[q.unit];
  return nutrient.unit === "mcg" ? mg / MASS_MG.mcg : mg;
}

// ---- Compound mass vs elemental mass (issue #2798) ----
//
// The dataset's figures are ELEMENTAL — dri.json's magnesium note says so — and the
// contract this module has always assumed is that a product states the elemental
// amount, which is what a Supplement Facts panel declares. That is why the baseline
// stack (Glycinate 400 mg + Citrate 200 mg) correctly sums to 600 mg of magnesium.
//
// The convention breaks for the FRONT-of-bottle number on a compound dosed by its
// total mass. "Magnesium L-Threonate 2 g" is two grams of the compound — about 165 mg
// of magnesium — and counting it as 2000 mg of magnesium raised an over-the-UL warning
// at roughly fourteen times the real exposure, on the most safety-critical number this
// app computes.
//
// THIS IS A UNIT QUESTION, NOT A DISCOUNT. Reading grams of a salt as grams of the
// metal is not a cautious total, it is a wrong one, and converting between them is the
// same kind of step as g → mg. The conservative-direction rule below governs
// OBLIGATION — whether an item counts, and at what weight — not what its number means.
//
// The app cannot see which convention a given entry used, so the reinterpretation is
// gated on the one thing it CAN see being decisive: an amount too large to be a
// labeled elemental dose. The ceiling is ~3x the largest elemental amount any single
// magnesium label states (about 500 mg), so:
//
//   * every item whose DAILY TOTAL is at or below the ceiling is counted exactly as
//     entered — no total that exists today moves at all;
//   * only a gram-scale daily total, on an item the user named by its compound form,
//     is re-read as that compound's mass.
//
// The ceiling is tested against the item's daily total, not against one dose row. The
// number it protects IS a daily total, and a per-row test let the whole defect through
// on any split schedule: Magtein's ordinary 1.5 g + 0.5 g regimen kept reading 2000 mg
// of magnesium because neither row cleared the bar on its own.
//
// Above the ceiling the correction can legitimately take a total under the UL — that is
// the point, since the number it replaces was wrong. What must never happen is the app
// choosing a reading LESS cautious than the label supports, so where a name matches
// several forms the LARGEST elemental fraction wins (see maxima below). Erring high is
// deliberate everywhere here: leaving an over-warn in place is recoverable, silencing a
// real exceedance is not. The fractions are stoichiometric (the metal's mass over the
// compound's formula mass), which is also the CAUTIOUS choice where a form's hydration
// varies — the threonate figure here (8.3%) is above the ~7.2% a Magtein label implies,
// so the elemental estimate errs upward.
//
// The table is magnesium-only on purpose: magnesium is the nutrient whose compound-mass
// labeling is documented here, and it carries a supplemental-basis UL, so its total is
// the one the app claims exactly. Another nutrient earns an entry when a real label
// shows the same failure, not on speculation.

interface CompoundForm {
  // Matched case-insensitively against the item name, AFTER the item has already
  // resolved to `nutrientKey` — so "Zinc Citrate" can never pick up a magnesium factor.
  pattern: RegExp;
  nutrientKey: string;
  label: string;
  // Mass of the element per unit mass of the compound.
  elementalFraction: number;
}

const COMPOUND_FORMS: CompoundForm[] = [
  {
    pattern: /l[\s-]?threonate|threonate|magtein/i,
    nutrientKey: "magnesium",
    label: "magnesium L-threonate",
    elementalFraction: 0.083,
  },
  {
    pattern: /bis[\s-]?glycinate|glycinate/i,
    nutrientKey: "magnesium",
    label: "magnesium glycinate",
    elementalFraction: 0.141,
  },
  {
    pattern: /citrate/i,
    nutrientKey: "magnesium",
    label: "magnesium citrate",
    elementalFraction: 0.162,
  },
  {
    pattern: /malate/i,
    nutrientKey: "magnesium",
    label: "magnesium malate",
    elementalFraction: 0.155,
  },
  {
    pattern: /taurate/i,
    nutrientKey: "magnesium",
    label: "magnesium taurate",
    elementalFraction: 0.089,
  },
  {
    // Anchored on the left: "Magnesium Hydroxide" contains "oxide" (hydr-OXIDE) and
    // used to take the oxide fraction, which then told the reader the app had read
    // "magnesium oxide" — naming a product they did not enter, on a safety surface.
    pattern: /(?<![a-z])oxide/i,
    nutrientKey: "magnesium",
    label: "magnesium oxide",
    elementalFraction: 0.603,
  },
  {
    // `magnesia` rides here rather than on the oxide entry above. Strictly the word
    // means the oxide, but the product the catalog actually meets is Milk of
    // Magnesia — a defined USP magnesium HYDROXIDE suspension — and reading it at
    // the oxide's 60.3% would name a compound the user never entered, the same copy
    // failure the anchored `oxide` pattern was written to stop. Without an entry at
    // all, "Milk of Magnesia" read 2400 mg where "Magnesium Hydroxide" — the
    // identical product — read 1000.8 mg: a 2.4x divergence between two names for
    // one thing (#2934 review).
    pattern: /hydroxide|\bmagnesia\b/i,
    nutrientKey: "magnesium",
    label: "magnesium hydroxide",
    elementalFraction: 0.417,
  },
];

// The largest amount, in a nutrient's canonical unit, that a single label plausibly
// states as the ELEMENT. Above it, an entry naming a compound form is that compound's
// total mass. Keyed by nutrient so it can never be read as a general dose threshold.
const STATED_ELEMENTAL_CEILING: Record<string, number> = {
  magnesium: 1500,
};

export interface ElementalReading {
  // In the nutrient's canonical unit.
  amount: number;
  // The recognized compound form, when the stated mass was re-read as compound mass;
  // null when the amount was taken exactly as entered.
  compound: string | null;
}

// Read an item's DAILY TOTAL (already unit-converted) as the nutrient's ELEMENTAL
// content. Returns the amount unchanged (and `compound: null`) unless BOTH gates hold:
// the total is above the nutrient's stated-elemental ceiling, and the item's name
// carries a recognized compound form for that same nutrient. Pure.
//
// When the name matches SEVERAL forms — "Magnesium Complex (Oxide, Citrate, Malate)",
// an ordinary blend — the one with the LARGEST elemental fraction wins. Taking the
// first declared match instead made the app pick a reading its own label contradicted:
// that 2 g blend read at citrate's 16.2% is 324 mg and silent, while the same 2 g read
// as the oxide the label also names is 1206 mg, 3.4x the UL. A blend is not a promise
// that the least concentrated named form is the whole product, so the ceiling gate can
// only stay honest if the reading is the most cautious one consistent with the name.
export function elementalReading(
  itemName: string,
  nutrient: DriNutrient,
  statedAmount: number
): ElementalReading {
  const ceiling = STATED_ELEMENTAL_CEILING[nutrient.key];
  if (ceiling == null || statedAmount <= ceiling) {
    return { amount: statedAmount, compound: null };
  }
  const form = COMPOUND_FORMS.filter(
    (f) => f.nutrientKey === nutrient.key && f.pattern.test(itemName)
  ).reduce<CompoundForm | null>(
    (best, f) =>
      best == null || f.elementalFraction > best.elementalFraction ? f : best,
    null
  );
  if (!form) return { amount: statedAmount, compound: null };
  return {
    amount: statedAmount * form.elementalFraction,
    compound: form.label,
  };
}

// ---- Age/sex band selection (pure, tested) ----

// The reference band for a nutrient at the given age/sex: the half-open
// [min_age, max_age) band containing `age`, preferring a sex-specific band over a
// sex-neutral one. Returns null when no band covers the age (e.g. an infant below
// the youngest band) — the nutrient is then not evaluated. A null age scores at the
// default adult age.
export function selectBand(
  nutrient: DriNutrient,
  ageYears: number | null,
  sex: Sex | null
): DriBand | null {
  const age = ageYears ?? DEFAULT_ADULT_AGE;
  const covering = nutrient.bands.filter(
    (b) => age >= b.min_age && (b.max_age == null || age < b.max_age)
  );
  if (covering.length === 0) return null;
  if (sex) {
    const exact = covering.find((b) => b.sex === sex);
    if (exact) return exact;
  }
  return covering.find((b) => b.sex == null) ?? covering[0];
}

// ---- Stack summation + UL check (pure, tested) ----

// THE CONSERVATIVE-DIRECTION RULE for obligation in this module (#1505).
//
// Obligation (`must` / `should` / `may`) is a statement about PUSHING — what the
// system may initiate about an item — not about pharmacology. So it must never move
// a safety-adjacent number in the reassuring direction. The catch is that "the
// reassuring direction" is not the same for the two questions this module answers,
// which is why there is one rule with two opposite consequences:
//
//   * The UL check is a RISK number. Bigger is worse. Obligation may never SHRINK
//     it, so an on-demand (`may`) item counts at FULL amount, exactly like a `must`
//     one, and the line simply LABELS that it did. Dropping it would erase the
//     exposure of the very items nothing is nudging about.
//
//   * The RDA adequacy note is a REASSURANCE number. Bigger reads as better
//     covered. Obligation may never INFLATE it, so the share is computed from
//     COMMITTED intake only (`must` + `should`) and the on-demand remainder is
//     reported as a labelled aside. Counting a bottle the user takes "sometimes"
//     toward "you're at 80% of the RDA" would overstate what they reliably get.
//
// Both surfaces therefore see every item; neither silently omits one. The rule is
// "label, don't drop" for risk and "exclude, then disclose" for reassurance.
//
// The upstream schedule gate (contributesToDailyLimit) stays obligation-blind for
// the same reason; obligation is applied HERE, per question, where the direction of
// caution is known.

// One item in the stack the checker sees — decoupled from the DB row so the pure
// tests can construct it directly. `doseAmounts` is the item's CURRENT scheduled
// dose amounts (one string per dose row, e.g. ["400 mg", "400 mg"] for a split
// dose); their nutrient content is summed for the item. `optional` marks an
// on-demand item (`may` obligation, formerly PRN): it still counts toward the UL
// total but is excluded from — and disclosed beside — the RDA share, per the
// conservative-direction rule above.
export interface StackItem {
  name: string;
  active: boolean;
  doseAmounts: (string | null)[];
  optional?: boolean;
  // The item's label composition (issue #2856), when the person has entered it: one
  // entry per ingredient, amounts already canonical and PER SINGLE DOSE UNIT. Absent
  // or empty for the overwhelming majority of items, which are named by the one thing
  // they contain and need no decomposition.
  ingredients?: readonly StackIngredient[];
}

// One label ingredient in the stack checker's input. `amount`/`unit` are null
// together when the label states no parseable quantity — the row still names a
// substance for the safety belts, it just cannot feed a nutrient total.
export interface StackIngredient {
  name: string;
  amount: number | null;
  unit: IngredientUnit | null;
}

export interface NutrientContribution {
  name: string;
  amount: number;
  optional?: boolean;
  // The ingredient rows that produced this amount (issue #2856), when the item's
  // COMPOSITION spoke louder than its name — e.g. "zinc" for an "Eye Health+"
  // capsule whose name mentions no mineral at all. Absent when the amount came from
  // the item's own name, which is the ordinary single-substance case.
  via?: string;
  // The compound form this item's stated mass was read as (issue #2798), when the
  // amount was too large to be a labeled ELEMENTAL dose — e.g. "magnesium
  // L-threonate" for a 2 g entry. Null/absent means the amount was counted exactly
  // as entered, which is the case for every dose at or below the ceiling.
  compound?: string;
}

// A nutrient's summed supplemental intake across the stack, with its UL/RDA for the
// profile's age/sex. `total`/`ul`/`rda` are in `unit`. `contributors` lists the
// items that contributed (for the evidence line), largest first. `optionalTotal` is
// the part of `total` coming from on-demand (`may`) items — always a SUBSET of
// `total`, never subtracted from it here, so each consumer can apply the
// conservative-direction rule for its own question.
export interface StackNutrientTotal {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  total: number;
  optionalTotal: number;
  ul: number | null;
  rda: number | null;
  contributors: NutrientContribution[];
}

// One item's daily contribution to one nutrient, before it joins the stack total.
interface ItemNutrientReading {
  amount: number;
  compound: string | null;
  via?: string;
}

// What ONE item contributes to each nutrient in a day — the whole of the
// name-vs-composition question, asked once, here (issue #2856).
//
// TWO READINGS, ONE VOCABULARY. An item can describe what it contains in two ways,
// and BOTH go through the SAME NAME_MATCHERS:
//
//   * its NAME, dosed by its dose amounts — the original reading, unchanged, and the
//     only one the vast majority of items have ("Zinc 30 mg");
//   * its INGREDIENT ROWS, each dosed per label unit and multiplied by the number of
//     units taken that day — the reading a blend has ("Eye Health+ · 1 cap", whose
//     name matches no nutrient at all while its label states zinc 11 mg and copper
//     2 mg).
//
// The matchers are applied PER INGREDIENT rather than once per item name, which is
// the whole of phase 2: one matcher, wider input. Nothing is forked — an ingredient
// named "Zinc (as bisglycinate)" resolves through the same patterns, and the same
// excipient redaction, that "Zinc Bisglycinate" as an item name always has.
//
// WHY THE LARGER OF THE TWO, NOT THE SUM. A blend usually states the same substance
// twice — "Vitamin D3 + K2" dosed "2000 IU / 100 mcg" WITH an ingredient row reading
// vitamin D3 2000 IU — and adding those would double every such item's vitamin D
// overnight. Taking the larger keeps the invariant the issue states in both
// directions: composition can only WIDEN a total (a mistyped ingredient row can never
// talk an item's own labeled dose down), and it can never double-count the substance
// the item is named after.
function itemNutrientAmounts(
  item: StackItem
): Map<string, ItemNutrientReading> {
  const out = new Map<string, ItemNutrientReading>();

  // ── The item's own name, dosed by its dose rows (the original reading) ──────────
  const nameKey = resolveNutrientKey(item.name);
  const nameNutrient = nameKey ? BY_KEY.get(nameKey) : undefined;
  if (nameKey && nameNutrient) {
    // Sum the item's dose rows FIRST, then read the day's total as elemental (#2798).
    // The compound/elemental question is asked once per item, of the number it is
    // actually about: a person taking Magtein as 1.5 g + 0.5 g takes 2 g of the
    // compound a day, and asking it of each row separately answered "neither row is
    // gram-scale" and left the whole defect standing on every split schedule.
    let statedTotal = 0;
    let contributed = false;
    for (const amount of item.doseAmounts) {
      const q = parseQuantity(amount);
      if (!q) continue;
      const converted = toNutrientUnit(q, nameNutrient);
      if (converted == null) continue;
      statedTotal += converted;
      contributed = true;
    }
    if (contributed) {
      const reading = elementalReading(item.name, nameNutrient, statedTotal);
      out.set(nameKey, { amount: reading.amount, compound: reading.compound });
    }
  }

  // ── The item's label composition, dosed by label units taken per day ────────────
  const ingredients = item.ingredients ?? [];
  if (ingredients.length === 0) return out;
  // How many label units the day's schedule is. Summed across dose rows, so a blend
  // taken 1 cap morning + 1 cap evening is two capsules of everything on the label.
  const unitsPerDay = item.doseAmounts.reduce(
    (n, amount) => n + doseUnitCount(amount),
    0
  );
  if (unitsPerDay <= 0) return out;

  const composed = new Map<string, { amount: number; via: string[] }>();
  for (const ing of ingredients) {
    if (ing.amount == null || ing.unit == null) continue;
    const key = resolveNutrientKey(ing.name);
    if (!key) continue;
    const nutrient = BY_KEY.get(key);
    if (!nutrient) continue;
    const converted = toNutrientUnit(
      { value: ing.amount * unitsPerDay, unit: ing.unit },
      nutrient
    );
    if (converted == null) continue;
    // The compound/elemental re-read (#2798) applies per INGREDIENT ROW here, because
    // one row is one labeled compound — "Magnesium L-Threonate 2 g" on a line of a
    // blend's label means exactly what it means on the front of its own bottle.
    const reading = elementalReading(ing.name, nutrient, converted);
    const bucket = composed.get(key) ?? { amount: 0, via: [] };
    // Two rows CAN name one nutrient ("zinc picolinate" + "zinc gluconate"); those
    // genuinely sum — it is the same element twice, stated twice.
    bucket.amount += reading.amount;
    bucket.via.push(ing.name);
    composed.set(key, bucket);
  }

  for (const [key, bucket] of composed) {
    const fromName = out.get(key);
    if (fromName && fromName.amount >= bucket.amount) continue;
    out.set(key, {
      amount: bucket.amount,
      compound: null,
      via: bucket.via.join(" + "),
    });
  }
  return out;
}

// Sum the ACTIVE stack's daily supplemental intake per nutrient. Each active item's
// dose amounts are parsed → converted to the nutrient's canonical unit → summed;
// items are grouped by nutrient so two magnesium products sum into one magnesium
// total. An item that carries LABEL COMPOSITION (#2856) also contributes through its
// ingredient rows — see itemNutrientAmounts — so a blend's zinc finally stacks
// against a standalone zinc. Nutrients with no resolvable quantity (all "1 capsule",
// no ingredients) don't appear.
// `ageYears`/`sex` select the UL/RDA band. Results are in nutrient (dataset) order.
export function summarizeStack(
  items: StackItem[],
  ageYears: number | null,
  sex: Sex | null
): StackNutrientTotal[] {
  const totals = new Map<
    string,
    {
      amount: number;
      optionalAmount: number;
      contributors: NutrientContribution[];
    }
  >();

  for (const item of items) {
    if (!item.active) continue;
    for (const [key, reading] of itemNutrientAmounts(item)) {
      const bucket = totals.get(key) ?? {
        amount: 0,
        optionalAmount: 0,
        contributors: [],
      };
      bucket.amount += reading.amount;
      if (item.optional) bucket.optionalAmount += reading.amount;
      bucket.contributors.push({
        name: item.name,
        amount: reading.amount,
        optional: item.optional ? true : undefined,
        compound: reading.compound ?? undefined,
        via: reading.via,
      });
      totals.set(key, bucket);
    }
  }

  const out: StackNutrientTotal[] = [];
  for (const nutrient of NUTRIENTS) {
    const bucket = totals.get(nutrient.key);
    if (!bucket) continue;
    const band = selectBand(nutrient, ageYears, sex);
    out.push({
      key: nutrient.key,
      label: nutrient.label,
      unit: nutrient.unit,
      basis: nutrient.basis,
      total: bucket.amount,
      optionalTotal: bucket.optionalAmount,
      ul: band?.ul ?? null,
      rda: band?.rda ?? null,
      contributors: bucket.contributors.sort((a, b) => b.amount - a.amount),
    });
  }
  return out;
}

// A nutrient whose stack total EXCEEDS its UL — the payload behind both the
// the intake surfaces warning row and the dismissible Upcoming finding.
// `includesOptional` is true when at least one on-demand (`may`) item fed the total.
// The amount is NOT reduced — per the conservative-direction rule a risk number may
// never shrink because of an obligation — the flag exists so the detail line can say
// so out loud.
export interface UlWarning {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  total: number;
  ul: number;
  includesOptional: boolean;
  contributors: NutrientContribution[];
}

// The over-UL subset of the stack: nutrients whose summed supplemental intake is
// STRICTLY GREATER than the UL for the profile's age/sex. A total exactly AT the UL
// is not flagged (the UL is the highest intake likely to pose no risk). Nutrients
// with no UL for the band are skipped.
export function stackUlWarnings(
  items: StackItem[],
  ageYears: number | null,
  sex: Sex | null
): UlWarning[] {
  return summarizeStack(items, ageYears, sex)
    .filter((t): t is StackNutrientTotal & { ul: number } => t.ul != null)
    .filter((t) => t.total > t.ul)
    .map((t) => ({
      key: t.key,
      label: t.label,
      unit: t.unit,
      basis: t.basis,
      total: t.total,
      ul: t.ul,
      includesOptional: t.optionalTotal > 0,
      contributors: t.contributors,
    }));
}

// ---- Formatting (shared by every surface) ----

// Round an intake amount for display: whole numbers stay whole, otherwise at most
// one decimal (so 50 mcg reads "50", 349.5 mg reads "349.5").
export function fmtAmount(n: number): string {
  const rounded = Math.round(n * 10) / 10;
  return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(1);
}

// The stable suppression/identity key for a dietary-limit finding: one per nutrient
// (`dietary-limit:<key>`), so a dismissal follows the nutrient — a magnesium
// dismissal stays put while a later vitamin-D exceedance surfaces on its own key.
// The SINGLE source of truth for the key (the Upcoming item and any future push
// derive from it), mirroring refillSignalKey.
export function dietaryLimitSignalKey(nutrientKey: string): string {
  return `dietary-limit:${nutrientKey}`;
}

export function ulWarningTitle(w: UlWarning): string {
  return `${w.label} above the upper limit`;
}

// A caveat appended to a UL line when an active condition makes the POPULATION UL
// unreliable for this nutrient (issue #657). The bands here are age/sex only, so a
// condition that lowers a nutrient's safe ceiling (CKD × magnesium is the anchor)
// isn't captured by the band — this annotates the line rather than silently trusting
// the population figure. Reuses the SAME curated drop-severity condition→nutrient data
// the food engine and the supplement belt use (lib/condition-nutrient), so the three
// surfaces can't disagree. Returns null when no active condition qualifies. Never
// prescriptive.
export function ulConditionCaveat(
  nutrientKey: string,
  conditions: readonly ConditionInput[]
): string | null {
  const hits = conditionsContraindicatingNutrient(nutrientKey, conditions);
  if (hits.length === 0) return null;
  const label = BY_KEY.get(nutrientKey)?.label.toLowerCase() ?? nutrientKey;
  return (
    `You have ${hits[0].condition} on file — the population upper limit for ` +
    `supplemental ${label} may not apply to you; discuss with your clinician.`
  );
}

// The informational, never-prescriptive detail line. Wording respects the basis:
// a supplemental-only UL states the stack total directly; a total-intake UL notes
// that food adds still more. When an on-demand item fed the total, the line SAYS so
// (#1505) — the amount is never reduced, but the user is told what it counted, so a
// total they don't take every single day is explained rather than mysterious. An
// optional condition caveat (ulConditionCaveat) is appended when the population UL
// may be unreliable for an active condition (#657).
export function ulWarningDetail(
  w: UlWarning,
  conditionCaveat?: string | null
): string {
  const amt = `${fmtAmount(w.total)} ${w.unit}`;
  const ul = `${fmtAmount(w.ul)} ${w.unit}`;
  const lead =
    w.basis === "supplemental"
      ? `Your supplements total about ${amt}/day of supplemental ${w.label} — above the ${ul} Tolerable Upper Intake Level (UL) for your age.`
      : `Your supplements alone total about ${amt}/day of ${w.label} — above the ${ul} Tolerable Upper Intake Level (UL) for total intake at your age, and food and drink add still more.`;
  const inclusion = w.includesOptional
    ? " This total counts every item that supplements it, including as-needed items."
    : "";
  const base = `${lead}${inclusion}${compoundNote(w.contributors, w.label)} Discuss with your clinician before changing anything.`;
  return conditionCaveat ? `${base} ${conditionCaveat}` : base;
}

// Say out loud when an amount was read as a compound's total mass rather than as the
// element (#2798), naming the form, so the number is checkable against the bottle
// instead of appearing from nowhere. Empty when every amount was counted as entered.
function compoundNote(
  contributors: readonly NutrientContribution[],
  label: string
): string {
  const forms = [
    ...new Set(
      contributors.map((c) => c.compound).filter((f): f is string => f != null)
    ),
  ];
  if (forms.length === 0) return "";
  const nutrient = label.toLowerCase();
  return (
    ` The amount you entered for ${forms.join(" and ")} is the compound's total` +
    ` weight, so this counts the ${nutrient} in it.`
  );
}

// One contributor's line: its per-item amount, marked "elemental" when the entered
// amount was the compound's weight so the two numbers can't be confused, and naming
// the INGREDIENT when the amount came from the item's label composition rather than
// its name (#2856) — otherwise "Eye Health+ 11 mg" on a zinc line reads as a number
// from nowhere, on a product whose name mentions no mineral.
function contributorLine(c: NutrientContribution, unit: string): string {
  const via = c.via ? ` (${c.via})` : "";
  return `${c.name}${via} ${fmtAmount(c.amount)} ${unit}${c.compound ? " elemental" : ""}`;
}

// A short "what's contributing" evidence line: the items feeding the total, each
// with its per-item amount, largest first.
export function ulWarningEvidence(w: UlWarning): string {
  return w.contributors.map((c) => contributorLine(c, w.unit)).join(" + ");
}

// ---- RDA adequacy (issue #578): the INVERSE of the UL check ----
//
// The UL check asks "does the stack ALONE exceed the safe ceiling?" — and because
// supplements-alone over a UL is definitely over once food is added, an exceedance is
// a DEFINITE fact. Adequacy is the mirror image and NOT symmetric: food intake is
// unknown, so the stack providing only X% of the RDA is NOT a definite shortfall — the
// user almost certainly gets the rest from food. So this reports, for a nutrient the
// stack is ACTIVELY supplementing, how much of the RDA those supplements ALONE cover —
// "your supplements provide X% of the RDA," never "you are deficient." The `basis`
// flag is carried through for parity but the wording is uniform here (an RDA is a
// total-diet requirement regardless of a UL's supplemental/total basis).

// A nutrient the stack supplements at BELOW its RDA, with the share the supplements
// alone cover. `total` and `sharePct` are COMMITTED intake only — `must` + `should`
// items — because this is a reassurance number and an obligation may never inflate
// one (see the conservative-direction rule at the top of this module). `optionalTotal`
// is the on-demand remainder, reported as a labelled aside rather than folded in.
// `sharePct` is committed/rda as a percent (0–99, since >= 100 is not a shortfall).
// Payload behind the intake surface adequacy row.
export interface RdaAdequacy {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  total: number;
  optionalTotal: number;
  rda: number;
  sharePct: number;
  contributors: NutrientContribution[];
}

// The below-RDA subset of the stack: nutrients the active stack ACTUALLY contributes
// (so a nutrient the user isn't supplementing never shows — we won't imply a food gap
// we can't see) whose COMMITTED supplemental total is STRICTLY BELOW the RDA for the
// profile's age/sex. A committed total at/above the RDA is not reported (the stack
// already meets it on its own). Nutrients with no RDA for the band (e.g. boron) are
// skipped. Dataset order.
//
// "Committed" excludes on-demand (`may`) items (#1505): the share is a reassurance
// figure, so it counts only what the user has actually committed to taking, and the
// on-demand remainder rides along as `optionalTotal` for the detail line to disclose.
// A nutrient supplemented ONLY on demand still appears — with a 0-ish committed share
// and the aside — rather than vanishing, so the surface never goes quiet about a
// nutrient the user is supplementing.
export function stackRdaAdequacy(
  items: StackItem[],
  ageYears: number | null,
  sex: Sex | null
): RdaAdequacy[] {
  return summarizeStack(items, ageYears, sex)
    .filter((t): t is StackNutrientTotal & { rda: number } => t.rda != null)
    .map((t) => ({ t, committed: t.total - t.optionalTotal }))
    .filter(({ t, committed }) => committed > 0 || t.optionalTotal > 0)
    .filter(({ t, committed }) => committed < t.rda)
    .map(({ t, committed }) => ({
      key: t.key,
      label: t.label,
      unit: t.unit,
      basis: t.basis,
      total: committed,
      optionalTotal: t.optionalTotal,
      rda: t.rda,
      sharePct: Math.round((committed / t.rda) * 100),
      contributors: t.contributors,
    }));
}

// The suppression/identity key for an adequacy note: one per nutrient
// (`rda-adequacy:<key>`). Deliberately DISTINCT from dietaryLimitSignalKey — a
// dismissal of the "over-UL magnesium" warning must not also silence the (unrelated)
// "40% of the folate RDA" note, and vice-versa.
export function rdaAdequacySignalKey(nutrientKey: string): string {
  return `rda-adequacy:${nutrientKey}`;
}

export function rdaAdequacyTitle(a: RdaAdequacy): string {
  return `${a.label}: supplements provide ${a.sharePct}% of the RDA`;
}

// The informational detail. The load-bearing wording (#578): "your supplements alone
// provide X% of the RDA" — NEVER "you are deficient," because food (unknown here)
// makes up the rest. This is the inverse of the UL case's definite-exceedance wording.
export function rdaAdequacyDetail(a: RdaAdequacy): string {
  const amt = `${fmtAmount(a.total)} ${a.unit}`;
  const rda = `${fmtAmount(a.rda)} ${a.unit}`;
  const base =
    `Your supplements alone provide about ${amt}/day of ${a.label} — roughly ${a.sharePct}% of the ${rda}/day RDA for your age. ` +
    `Food provides the rest, so a low share here does NOT mean a shortfall — it's just what your stack contributes.`;
  // The on-demand aside (#1505): named, but explicitly outside the share, so the
  // percentage stays a figure the user can rely on rather than one propped up by
  // bottles they only reach for sometimes.
  const aside =
    a.optionalTotal > 0
      ? ` A further ${fmtAmount(a.optionalTotal)} ${a.unit}/day comes from as-needed items, which aren't counted toward this share.`
      : "";
  return `${base}${aside}`;
}

// The "what's contributing" evidence line, mirroring ulWarningEvidence.
export function rdaAdequacyEvidence(a: RdaAdequacy): string {
  return a.contributors.map((c) => contributorLine(c, a.unit)).join(" + ");
}
