// Pure supplement stack-total UL checker (issue #148) — the supplement-side twin
// of drug-interaction checking. Given a profile's active supplement/medication
// stack (each item's scheduled dose amounts) plus its age/sex, it sums the daily
// intake PER NUTRIENT and flags any nutrient whose stack total exceeds the NIH
// Tolerable Upper Intake Level (UL). No DB, no network — the DB gather lives in
// lib/queries/intake.ts (getDietaryLimitWarnings), which calls the pure functions
// here so the /medicine warning row and the dismissible Upcoming finding are
// formatters over ONE computation (AGENTS.md "one question, one computation").
//
// The reference values (UL/RDA by age/sex, the supplemental-vs-total `basis`, the
// IU factors) come from the committed lib/dri.json, generated by scripts/gen-dri.ts
// from PUBLIC-DOMAIN NIH DRI tables. The supplement-name → nutrient vocabulary
// lives HERE (NAME_MATCHERS) — the app's supplement catalog is what we recognize;
// the dataset is the reference figures. lib/__tests__/dri-dataset.test.ts pins that
// every nutrient a matcher references exists in the dataset (anti-drift), and that
// the committed JSON is a fixed point of the generator.
//
// CRITICAL — supplemental vs total basis: a supplemental-basis UL (magnesium,
// niacin, folic acid, supplemental vitamin E) is defined over supplement intake
// alone, so "your stack totals X, the UL is Y" is exact. A total-basis UL (vitamin
// A, D, calcium, iron, …) is defined over intake from ALL sources; the app only
// knows supplements, so exceeding a total UL from supplements alone is a definite
// exceedance (food only adds more) but the copy must say so. Both surface a warning
// when the supplemental sum exceeds the UL — the `basis` flag drives the WORDING.
// Everything here is INFORMATIONAL, never prescriptive: the copy is "discuss with
// your clinician", never "stop taking X".

import driData from "./dri.json";
import type { Sex } from "./types";

export interface DriBand {
  min_age: number;
  max_age: number | null;
  sex?: "male" | "female";
  ul: number | null;
  rda: number | null;
}

export interface DriNutrient {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  iu?: number | null;
  note?: string | null;
  bands: DriBand[];
}

const NUTRIENTS = (driData as { nutrients: DriNutrient[] }).nutrients;
const BY_KEY = new Map(NUTRIENTS.map((n) => [n.key, n]));

// When the profile's age is unknown, score against a default ADULT age: adult ULs
// are the most permissive band for every nutrient here, so an unknown-age adult is
// never OVER-flagged against a stricter child band it may not belong to.
export const DEFAULT_ADULT_AGE = 30;

// Supplement/medication NAME → nutrient key. Ordered; the first matching pattern
// wins. Patterns are matched case-insensitively against the item name. This is the
// app's recognized vocabulary (the supplement catalog): a name that matches nothing
// (a multivitamin, a herb, a protein) contributes to no nutrient total — a
// documented fallback, pinned by the dataset test to only ever reference real keys.
// Every key here MUST exist in dri.json.
const NAME_MATCHERS: { pattern: RegExp; key: string }[] = [
  { pattern: /magnesium/i, key: "magnesium" },
  { pattern: /\bzinc\b/i, key: "zinc" },
  { pattern: /\bcalcium\b/i, key: "calcium" },
  { pattern: /\biron\b/i, key: "iron" },
  { pattern: /\bselenium\b/i, key: "selenium" },
  { pattern: /\bcopper\b/i, key: "copper" },
  { pattern: /\bmanganese\b/i, key: "manganese" },
  { pattern: /\biodine\b/i, key: "iodine" },
  { pattern: /\bmolybdenum\b/i, key: "molybdenum" },
  { pattern: /\bboron\b/i, key: "boron" },
  { pattern: /vitamin\s*b6|pyridoxine/i, key: "vitamin_b6" },
  { pattern: /niacin|nicotinic\s*acid|niacinamide/i, key: "niacin" },
  { pattern: /\bfolate\b|folic\s*acid/i, key: "folate" },
  { pattern: /vitamin\s*a\b/i, key: "vitamin_a" },
  { pattern: /vitamin\s*c\b/i, key: "vitamin_c" },
  { pattern: /vitamin\s*d/i, key: "vitamin_d" },
  { pattern: /vitamin\s*e\b/i, key: "vitamin_e" },
];

// Every nutrient key the matchers can resolve — exported so the dataset test can
// assert each resolves in dri.json (anti-drift).
export const MATCHER_KEYS: string[] = [
  ...new Set(NAME_MATCHERS.map((m) => m.key)),
];

// Resolve a supplement/medication name to a nutrient key, or null when it maps to
// no UL-bearing nutrient (the common case for herbs, proteins, multivitamins).
export function resolveNutrientKey(name: string): string | null {
  for (const m of NAME_MATCHERS) if (m.pattern.test(name)) return m.key;
  return null;
}

export function nutrientByKey(key: string): DriNutrient | undefined {
  return BY_KEY.get(key);
}

// ---- Unit parsing + conversion (pure, tested) ----

export type DoseUnit = "mg" | "mcg" | "g" | "iu";

export interface ParsedQuantity {
  value: number;
  unit: DoseUnit;
}

// Parse the leading quantity out of a dose amount string ("400 mg", "5000 IU",
// "200 mcg", "5 g", "1.5 g"). Returns the FIRST number+unit found — so a combo
// amount like "2000 IU / 100 mcg" (Vitamin D3 + K2) yields the leading nutrient's
// 2000 IU. A non-quantitative amount ("1 capsule", "1 scoop", null) returns null:
// its nutrient content is unknown, so it's excluded (documented fallback). "mcg",
// "µg" and "ug" all normalize to mcg; unit match is case-insensitive.
export function parseQuantity(amount: string | null): ParsedQuantity | null {
  if (!amount) return null;
  const m = amount.match(/(\d+(?:\.\d+)?)\s*(mcg|µg|ug|mg|g|iu)\b/i);
  if (!m) return null;
  const value = Number(m[1]);
  if (!Number.isFinite(value)) return null;
  let u = m[2].toLowerCase();
  if (u === "µg" || u === "ug") u = "mcg";
  return { value, unit: u as DoseUnit };
}

// Milligrams-per-unit for the mass units, used to convert any mass dose into a
// nutrient's canonical unit (mg or mcg).
const MASS_MG: Record<"mg" | "mcg" | "g", number> = {
  g: 1000,
  mg: 1,
  mcg: 0.001,
};

// Convert a parsed dose quantity into the nutrient's canonical unit, or null when
// it can't be converted (an IU dose for a nutrient with no IU factor). Mass units
// convert generically via milligrams; an IU dose uses the nutrient's `iu` factor
// (canonical units per IU, e.g. vitamin D 0.025 mcg/IU).
export function toNutrientUnit(
  q: ParsedQuantity,
  nutrient: DriNutrient
): number | null {
  if (q.unit === "iu") {
    if (nutrient.iu == null) return null;
    return q.value * nutrient.iu;
  }
  // Mass → canonical mg, then mg → canonical unit.
  const mg = q.value * MASS_MG[q.unit];
  return nutrient.unit === "mcg" ? mg / MASS_MG.mcg : mg;
}

// ---- Age/sex band selection (pure, tested) ----

// The reference band for a nutrient at the given age/sex: the half-open
// [min_age, max_age) band containing `age`, preferring a sex-specific band over a
// sex-neutral one. Returns null when no band covers the age (e.g. an infant below
// the youngest band) — the nutrient is then not evaluated. A null age scores at the
// default adult age.
export function selectBand(
  nutrient: DriNutrient,
  ageYears: number | null,
  sex: Sex | null
): DriBand | null {
  const age = ageYears ?? DEFAULT_ADULT_AGE;
  const covering = nutrient.bands.filter(
    (b) => age >= b.min_age && (b.max_age == null || age < b.max_age)
  );
  if (covering.length === 0) return null;
  if (sex) {
    const exact = covering.find((b) => b.sex === sex);
    if (exact) return exact;
  }
  return covering.find((b) => b.sex == null) ?? covering[0];
}

// ---- Stack summation + UL check (pure, tested) ----

// One item in the stack the checker sees — decoupled from the DB row so the pure
// tests can construct it directly. `doseAmounts` is the item's CURRENT scheduled
// dose amounts (one string per dose row, e.g. ["400 mg", "400 mg"] for a split
// dose); their nutrient content is summed for the item.
export interface StackItem {
  name: string;
  active: boolean;
  doseAmounts: (string | null)[];
}

export interface NutrientContribution {
  name: string;
  amount: number;
}

// A nutrient's summed supplemental intake across the stack, with its UL/RDA for the
// profile's age/sex. `total`/`ul`/`rda` are in `unit`. `contributors` lists the
// items that contributed (for the evidence line), largest first.
export interface StackNutrientTotal {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  total: number;
  ul: number | null;
  rda: number | null;
  contributors: NutrientContribution[];
}

// Sum the ACTIVE stack's daily supplemental intake per nutrient. Each active item's
// dose amounts are parsed → converted to the nutrient's canonical unit → summed;
// items are grouped by nutrient so two magnesium products sum into one magnesium
// total. Nutrients with no resolvable quantity (all "1 capsule") don't appear.
// `ageYears`/`sex` select the UL/RDA band. Results are in nutrient (dataset) order.
export function summarizeStack(
  items: StackItem[],
  ageYears: number | null,
  sex: Sex | null
): StackNutrientTotal[] {
  const totals = new Map<
    string,
    { amount: number; contributors: NutrientContribution[] }
  >();

  for (const item of items) {
    if (!item.active) continue;
    const key = resolveNutrientKey(item.name);
    if (!key) continue;
    const nutrient = BY_KEY.get(key);
    if (!nutrient) continue;

    let itemAmount = 0;
    let contributed = false;
    for (const amount of item.doseAmounts) {
      const q = parseQuantity(amount);
      if (!q) continue;
      const converted = toNutrientUnit(q, nutrient);
      if (converted == null) continue;
      itemAmount += converted;
      contributed = true;
    }
    if (!contributed) continue;

    const bucket = totals.get(key) ?? { amount: 0, contributors: [] };
    bucket.amount += itemAmount;
    bucket.contributors.push({ name: item.name, amount: itemAmount });
    totals.set(key, bucket);
  }

  const out: StackNutrientTotal[] = [];
  for (const nutrient of NUTRIENTS) {
    const bucket = totals.get(nutrient.key);
    if (!bucket) continue;
    const band = selectBand(nutrient, ageYears, sex);
    out.push({
      key: nutrient.key,
      label: nutrient.label,
      unit: nutrient.unit,
      basis: nutrient.basis,
      total: bucket.amount,
      ul: band?.ul ?? null,
      rda: band?.rda ?? null,
      contributors: bucket.contributors.sort((a, b) => b.amount - a.amount),
    });
  }
  return out;
}

// A nutrient whose stack total EXCEEDS its UL — the payload behind both the
// /medicine warning row and the dismissible Upcoming finding.
export interface UlWarning {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  total: number;
  ul: number;
  contributors: NutrientContribution[];
}

// The over-UL subset of the stack: nutrients whose summed supplemental intake is
// STRICTLY GREATER than the UL for the profile's age/sex. A total exactly AT the UL
// is not flagged (the UL is the highest intake likely to pose no risk). Nutrients
// with no UL for the band are skipped.
export function stackUlWarnings(
  items: StackItem[],
  ageYears: number | null,
  sex: Sex | null
): UlWarning[] {
  return summarizeStack(items, ageYears, sex)
    .filter((t): t is StackNutrientTotal & { ul: number } => t.ul != null)
    .filter((t) => t.total > t.ul)
    .map((t) => ({
      key: t.key,
      label: t.label,
      unit: t.unit,
      basis: t.basis,
      total: t.total,
      ul: t.ul,
      contributors: t.contributors,
    }));
}

// ---- Formatting (shared by every surface) ----

// Round an intake amount for display: whole numbers stay whole, otherwise at most
// one decimal (so 50 mcg reads "50", 349.5 mg reads "349.5").
export function fmtAmount(n: number): string {
  const rounded = Math.round(n * 10) / 10;
  return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(1);
}

// The stable suppression/identity key for a dietary-limit finding: one per nutrient
// (`dietary-limit:<key>`), so a dismissal follows the nutrient — a magnesium
// dismissal stays put while a later vitamin-D exceedance surfaces on its own key.
// The SINGLE source of truth for the key (the Upcoming item and any future push
// derive from it), mirroring refillSignalKey.
export function dietaryLimitSignalKey(nutrientKey: string): string {
  return `dietary-limit:${nutrientKey}`;
}

export function ulWarningTitle(w: UlWarning): string {
  return `${w.label} above the upper limit`;
}

// The informational, never-prescriptive detail line. Wording respects the basis:
// a supplemental-only UL states the stack total directly; a total-intake UL notes
// that food adds still more.
export function ulWarningDetail(w: UlWarning): string {
  const amt = `${fmtAmount(w.total)} ${w.unit}`;
  const ul = `${fmtAmount(w.ul)} ${w.unit}`;
  const lead =
    w.basis === "supplemental"
      ? `Your supplements total about ${amt}/day of supplemental ${w.label} — above the ${ul} Tolerable Upper Intake Level (UL) for your age.`
      : `Your supplements alone total about ${amt}/day of ${w.label} — above the ${ul} Tolerable Upper Intake Level (UL) for total intake at your age, and food and drink add still more.`;
  return `${lead} This is informational, not a diagnosis — discuss with your clinician before changing anything.`;
}

// A short "what's contributing" evidence line: the items feeding the total, each
// with its per-item amount, largest first.
export function ulWarningEvidence(w: UlWarning): string {
  return w.contributors
    .map((c) => `${c.name} ${fmtAmount(c.amount)} ${w.unit}`)
    .join(" + ");
}

// ---- RDA adequacy (issue #578): the INVERSE of the UL check ----
//
// The UL check asks "does the stack ALONE exceed the safe ceiling?" — and because
// supplements-alone over a UL is definitely over once food is added, an exceedance is
// a DEFINITE fact. Adequacy is the mirror image and NOT symmetric: food intake is
// unknown, so the stack providing only X% of the RDA is NOT a definite shortfall — the
// user almost certainly gets the rest from food. So this reports, for a nutrient the
// stack is ACTIVELY supplementing, how much of the RDA those supplements ALONE cover —
// "your supplements provide X% of the RDA," never "you are deficient." The `basis`
// flag is carried through for parity but the wording is uniform here (an RDA is a
// total-diet requirement regardless of a UL's supplemental/total basis).

// A nutrient the stack supplements at BELOW its RDA, with the share the supplements
// alone cover. `sharePct` is total/rda as a percent (0–99, since >= 100 is not a
// shortfall). Payload behind the /medicine adequacy row.
export interface RdaAdequacy {
  key: string;
  label: string;
  unit: "mg" | "mcg";
  basis: "supplemental" | "total";
  total: number;
  rda: number;
  sharePct: number;
  contributors: NutrientContribution[];
}

// The below-RDA subset of the stack: nutrients the active stack ACTUALLY contributes
// (so a nutrient the user isn't supplementing never shows — we won't imply a food gap
// we can't see) whose supplemental total is STRICTLY BELOW the RDA for the profile's
// age/sex. A total at/above the RDA is not reported (the stack already meets it on its
// own). Nutrients with no RDA for the band (e.g. boron) are skipped. Dataset order.
export function stackRdaAdequacy(
  items: StackItem[],
  ageYears: number | null,
  sex: Sex | null
): RdaAdequacy[] {
  return summarizeStack(items, ageYears, sex)
    .filter((t): t is StackNutrientTotal & { rda: number } => t.rda != null)
    .filter((t) => t.total < t.rda)
    .map((t) => ({
      key: t.key,
      label: t.label,
      unit: t.unit,
      basis: t.basis,
      total: t.total,
      rda: t.rda,
      sharePct: Math.round((t.total / t.rda) * 100),
      contributors: t.contributors,
    }));
}

// The suppression/identity key for an adequacy note: one per nutrient
// (`rda-adequacy:<key>`). Deliberately DISTINCT from dietaryLimitSignalKey — a
// dismissal of the "over-UL magnesium" warning must not also silence the (unrelated)
// "40% of the folate RDA" note, and vice-versa.
export function rdaAdequacySignalKey(nutrientKey: string): string {
  return `rda-adequacy:${nutrientKey}`;
}

export function rdaAdequacyTitle(a: RdaAdequacy): string {
  return `${a.label}: supplements provide ${a.sharePct}% of the RDA`;
}

// The informational detail. The load-bearing wording (#578): "your supplements alone
// provide X% of the RDA" — NEVER "you are deficient," because food (unknown here)
// makes up the rest. This is the inverse of the UL case's definite-exceedance wording.
export function rdaAdequacyDetail(a: RdaAdequacy): string {
  const amt = `${fmtAmount(a.total)} ${a.unit}`;
  const rda = `${fmtAmount(a.rda)} ${a.unit}`;
  return (
    `Your supplements alone provide about ${amt}/day of ${a.label} — roughly ${a.sharePct}% of the ${rda}/day RDA for your age. ` +
    `Food provides the rest, so a low share here does NOT mean a shortfall — it's just what your stack contributes. Informational, not medical advice.`
  );
}

// The "what's contributing" evidence line, mirroring ulWarningEvidence.
export function rdaAdequacyEvidence(a: RdaAdequacy): string {
  return a.contributors
    .map((c) => `${c.name} ${fmtAmount(c.amount)} ${a.unit}`)
    .join(" + ");
}
