// Pure drug-/supplement-interaction detection (issue #144) — the drug-side twin of
// the stack-total UL checker (lib/dri.ts). No DB, no network: given a profile's
// ACTIVE supplement + medication stack (each item's name, cached RxCUI, active
// flag), it returns the known interacting PAIRS, severity-ranked, each with a
// one-line mechanism + citation. The DB gather lives in lib/queries/intake.ts
// (getInteractionWarnings), which calls the pure functions here so the /medicine
// warning row, the create/edit inline notice, and the dismissible Upcoming finding
// are all formatters over ONE computation (AGENTS.md "one question, one computation").
//
// The interaction facts + the name→concept vocabulary come from the curated-dataset
// framework (lib/datasets/drug-interactions.ts over the committed
// lib/datasets/data/drug-interactions.json, generated by
// scripts/gen-drug-interactions.ts from PUBLIC-DOMAIN FDA/DailyMed labeling, NIH refs,
// and RxNorm). Matching resolves each
// item to a drug CONCEPT (an ingredient or a class like "nsaid"/"ssri") by RxCUI
// (authoritative) or, failing that, by a normalized name/synonym match. The code
// match tries EVERY CUI the item carries — the confirmed (possibly product-level)
// rxcui plus its cached active-ingredient CUIs (issue #279) — so a combination
// medication ("Hyzaar", losartan/HCTZ) resolves to each ingredient's concept
// independently instead of silently matching nothing.
//
// EVERYTHING HERE IS INFORMATIONAL, never prescriptive: the copy is "discuss with
// your prescriber/pharmacist", never "stop taking X". Absence of a flag does NOT
// mean a combination is safe — the dataset is a curated high-value subset.

import { DRUG_CONCEPTS, DRUG_INTERACTIONS } from "./datasets/drug-interactions";

export type Severity = "major" | "moderate" | "minor";

// A matchable drug/drug-class concept: an ingredient (or class) with the RxNorm
// ingredient CUIs and lay/brand synonyms an active stack item resolves to. Exported
// so the PGx cross-check (lib/pgx.ts, issue #710) can REUSE the same RxCUI/name
// matcher (matchConceptKeysIn below) instead of hand-rolling a second one.
export interface Concept {
  key: string;
  label: string;
  rxcuis: string[];
  synonyms: string[];
}

// The concept vocabulary + the interaction rules, from the framework-loaded dataset
// (lib/datasets/drug-interactions.ts). Rules also carry a `pair` identity field the
// detector ignores (it reads a/b); structurally a superset of what's needed here.
const CONCEPTS: Concept[] = DRUG_CONCEPTS;
const INTERACTIONS = DRUG_INTERACTIONS;
const BY_KEY = new Map(CONCEPTS.map((c) => [c.key, c]));

// Major first — drives the /medicine section order and the finding band.
export const SEVERITY_RANK: Record<Severity, number> = {
  major: 0,
  moderate: 1,
  minor: 2,
};

export const SEVERITY_LABEL: Record<Severity, string> = {
  major: "Major",
  moderate: "Moderate",
  minor: "Minor",
};

// The minimal item shape the detector needs. `active` gates a row out of detection
// (a paused med/supplement isn't in the stack); `rxcui` is the cached RxNorm CUI
// (null when never resolved — the row then matches by name only);
// `rxcuiIngredients` is the confirmed concept's cached active-ingredient CUIs
// (issue #279 — a combination product's product-level rxcui isn't in the
// ingredient-keyed dataset, so each ingredient is matched independently; optional,
// absent/null when never resolved).
export interface InteractionItem {
  id: number;
  name: string;
  rxcui: string | null;
  rxcuiIngredients?: string[] | null;
  active: boolean;
}

// One detected interaction between two of the profile's items, resolved to the
// most-severe matching rule for that pair.
export interface InteractionHit {
  aId: number;
  bId: number;
  aName: string;
  bName: string;
  severity: Severity;
  mechanism: string;
  source: string;
  // The stable suppression/identity key — keyed on the item-id PAIR (ids never
  // recycle, names do), so a dismiss/snooze follows the specific pair. Mirrors
  // refillSignalKey / dietaryLimitSignalKey.
  dedupeKey: string;
}

// Normalize a name/synonym to the matcher's canonical token form: lowercased,
// punctuation collapsed to single spaces. MUST match scripts/gen-drug-interactions
// .ts's normalizeTerm so the committed synonyms line up with a live item name.
function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

// Whether the normalized synonym appears as a CONTIGUOUS token subsequence of the
// normalized item name — a word-boundary match, so "iron" hits "Ferrous / Iron
// 65mg" but never "environ", and "st johns wort" hits "St. John's Wort 300mg".
function nameContains(itemNorm: string, synNorm: string): boolean {
  if (!synNorm) return false;
  const hay = ` ${itemNorm} `;
  const needle = ` ${synNorm} `;
  return hay.includes(needle);
}

// Every RxCUI an item carries: the confirmed (possibly product-level) rxcui plus
// its cached active-ingredient CUIs. A combination product resolves to concepts
// through its ingredients (issue #279); a single scalar could never match an
// ingredient-only concept list. Shared by the food-drug matcher.
export function itemRxcuis(item: {
  rxcui: string | null;
  rxcuiIngredients?: string[] | null;
}): Set<string> {
  const cuis = new Set<string>();
  const rxcui = item.rxcui?.trim();
  if (rxcui) cuis.add(rxcui);
  for (const ing of item.rxcuiIngredients ?? []) {
    const cui = ing.trim();
    if (cui) cuis.add(cui);
  }
  return cuis;
}

// Exported aliases for the drug-allergy cross-check (issue #1029): the SAME
// normalization + token-containment the concept matcher uses, so a DIRECT
// allergen-substance × med-name match folds punctuation/case identically to the
// class/synonym path (one matcher discipline, #482).
export const normalizeDrugTerm = normalize;
export const drugTermContains = nameContains;

// The set of concept keys an item resolves to WITHIN a given concept vocabulary.
// RxCUI is authoritative (an exact match of ANY of the item's CUIs — product-level or
// cached ingredient — against a concept's ingredient CUIs), and a name/synonym match
// is the fallback; both are collected so a mislabeled row still matches on whichever
// signal fits. The one matcher, shared by the drug-interaction detector and the PGx
// cross-check (lib/pgx.ts, #710) so the two can never disagree on how a med resolves.
export function matchConceptKeysIn(
  item: {
    name: string;
    rxcui: string | null;
    rxcuiIngredients?: string[] | null;
  },
  concepts: readonly Concept[]
): string[] {
  const keys = new Set<string>();
  const cuis = itemRxcuis(item);
  const itemNorm = normalize(item.name);
  for (const c of concepts) {
    if (c.rxcuis.some((cui) => cuis.has(cui))) {
      keys.add(c.key);
      continue;
    }
    if (c.synonyms.some((syn) => nameContains(itemNorm, syn))) {
      keys.add(c.key);
    }
  }
  return [...keys];
}

// The concept keys an item resolves to within the drug-INTERACTION vocabulary.
export function matchConceptKeys(item: {
  name: string;
  rxcui: string | null;
  rxcuiIngredients?: string[] | null;
}): string[] {
  return matchConceptKeysIn(item, CONCEPTS);
}

// The label of a concept key (for any surface that wants the class name).
export function conceptLabel(key: string): string | null {
  return BY_KEY.get(key)?.label ?? null;
}

// The stable suppression/identity key for an interacting pair: `interaction:<lo>-<hi>`
// over the two item ids (sorted so it's direction-independent). Keyed on IDS, never
// names — ids never recycle, names/codes do (AGENTS.md #203), so a rename never
// re-attaches a stale dismissal to a different pair. The SINGLE source of truth for
// the key: the Upcoming item and the /medicine row both derive from it.
export function interactionSignalKey(aId: number, bId: number): string {
  const [lo, hi] = aId <= bId ? [aId, bId] : [bId, aId];
  return `interaction:${lo}-${hi}`;
}

// Detect every known interaction among a stack of items. ONLY active items are
// considered (a paused item is out of the stack). Each unordered item PAIR yields at
// most one hit — the most-severe matching rule (so two items that share two rules
// surface once, at the worse severity) — deduped by the item-id pair. Result is
// severity-ranked (major first), then by the two names, for a deterministic order.
export function detectInteractions(items: InteractionItem[]): InteractionHit[] {
  const active = items.filter((it) => it.active);
  // item id → its resolved concept keys.
  const conceptsByItem = new Map<number, Set<string>>();
  for (const it of active) {
    conceptsByItem.set(it.id, new Set(matchConceptKeys(it)));
  }
  const byId = new Map(active.map((it) => [it.id, it]));

  // For each unordered item pair, the best (most severe) matching rule.
  const best = new Map<string, InteractionHit>();
  for (const rule of INTERACTIONS) {
    for (const x of active) {
      const xKeys = conceptsByItem.get(x.id)!;
      // x must supply one side of the rule.
      const xIsA = xKeys.has(rule.a);
      const xIsB = xKeys.has(rule.b);
      if (!xIsA && !xIsB) continue;
      for (const y of active) {
        if (y.id === x.id) continue;
        const yKeys = conceptsByItem.get(y.id)!;
        // The pair satisfies the rule when x/y cover a and b (either assignment).
        const covers =
          (xIsA && yKeys.has(rule.b)) || (xIsB && yKeys.has(rule.a));
        if (!covers) continue;
        const [loId, hiId] = x.id <= y.id ? [x.id, y.id] : [y.id, x.id];
        const pairKey = `${loId}-${hiId}`;
        const prev = best.get(pairKey);
        if (
          prev &&
          SEVERITY_RANK[prev.severity] <= SEVERITY_RANK[rule.severity]
        )
          continue;
        const lo = byId.get(loId)!;
        const hi = byId.get(hiId)!;
        best.set(pairKey, {
          aId: lo.id,
          bId: hi.id,
          aName: lo.name,
          bName: hi.name,
          severity: rule.severity,
          mechanism: rule.mechanism,
          source: rule.source,
          dedupeKey: interactionSignalKey(lo.id, hi.id),
        });
      }
    }
  }

  return [...best.values()].sort(
    (a, b) =>
      SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity] ||
      a.aName.localeCompare(b.aName) ||
      a.bName.localeCompare(b.bName)
  );
}

// The hits that involve a specific CANDIDATE item — the create/edit inline notice's
// computation. The candidate (id = 0, the not-yet-saved row) is detected against
// the rest of the stack; only hits touching it are returned. Reuses the one
// detectInteractions so the notice can never disagree with the /medicine section.
export function interactionsForCandidate(
  candidate: {
    name: string;
    rxcui: string | null;
    rxcuiIngredients?: string[] | null;
  },
  others: InteractionItem[]
): InteractionHit[] {
  const CANDIDATE_ID = 0;
  const hits = detectInteractions([
    {
      id: CANDIDATE_ID,
      name: candidate.name,
      rxcui: candidate.rxcui,
      rxcuiIngredients: candidate.rxcuiIngredients,
      active: true,
    },
    ...others.filter((o) => o.id !== CANDIDATE_ID),
  ]);
  return hits.filter((h) => h.aId === CANDIDATE_ID || h.bId === CANDIDATE_ID);
}

// ---- Formatting (shared by every surface) ----

// The warning title: the two interacting item names, e.g. "Warfarin + Ibuprofen".
export function interactionTitle(hit: InteractionHit): string {
  return `${hit.aName} + ${hit.bName}`;
}

// The informational, never-prescriptive detail line: severity + mechanism + source,
// closing with the "discuss with your prescriber" framing.
export function interactionDetail(hit: InteractionHit): string {
  return (
    `${SEVERITY_LABEL[hit.severity]} interaction. ${hit.mechanism} ` +
    `This is informational, not medical advice — discuss with your prescriber or ` +
    `pharmacist before changing anything. Source: ${hit.source}.`
  );
}
