// Pure age/sex percentile + fitness-age lookup over the baked fitness-norm dataset
// (lib/datasets/data/fitness-norms.json, generated by scripts/gen-fitness-norms.ts,
// consumed via lib/datasets/fitness-norms.ts) — issue #158.
//
// Turns a raw fitness measurement (VO2 Max, grip strength, 30-second chair stand,
// single-leg balance) into:
//   • PERCENTILE — where the value falls among same-age, same-sex peers, with band
//     INTERPOLATION (the norm value vector is interpolated linearly between the two
//     nearest age bands before the value is placed on it).
//   • FITNESS AGE — the age whose 50th-percentile value equals the measurement (the
//     inverse of the median curve). A higher-is-better value above your age's median
//     yields a younger fitness age.
//
// DB-free and pure so it's unit-tested in lib/__tests__. Age/sex come from
// profile_settings at the call site (getUserSex/getUserAgeOn in lib/settings). When
// sex or age is unset — or the subject is a child (adult-context norms) — every
// entry point returns null so the surfaces HIDE the percentile line, exactly like
// the other age/sex-gated biomarker surfaces.

import type { Sex } from "@/lib/types";
import {
  FITNESS_NORM_MARKERS_MAP,
  type MarkerNorms,
  type SexNorms,
  type NormBand,
  type Direction,
} from "@/lib/datasets/fitness-norms";
import { ADULT_MIN_AGE, isAdultForClinical } from "@/lib/life-stage";

const MARKERS: Record<string, MarkerNorms> = FITNESS_NORM_MARKERS_MAP;

// The canonical biomarker names that carry fitness norms (must match the JSON keys
// AND the canonical_biomarkers rows / vitals-input canonical names byte-for-byte).
export const FITNESS_NORM_MARKERS = Object.keys(MARKERS);

// Adult-context floor: the norms are adult reference standards, so a subject below
// this age hides the percentile line (matches how the pediatric/adult split hides
// adult ranges for children elsewhere). Re-exported from the one age model
// (lib/life-stage) so this and the other adult-population surfaces share one line.
export { ADULT_MIN_AGE };

export function hasFitnessNorms(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(MARKERS, name);
}

// Clamp flag: whether the answer sat at a table edge (so the surface can say
// "≥ 90th" / "top of range" rather than implying interpolated precision).
export type Clamp = "low" | "high" | null;

export interface FitnessPercentile {
  percentile: number; // 1..99, rounded
  clamped: Clamp;
}
export interface FitnessAgeResult {
  fitnessAge: number; // whole years, rounded
  clamped: Clamp; // "low" = fitter than the youngest band; "high" = below the oldest band
}
export interface FitnessContext {
  unit: string;
  source: string;
  percentile: FitnessPercentile;
  fitnessAge: FitnessAgeResult | null;
}

// Linear interpolation of the norm value vector at an exact age, between the two
// nearest bands; clamped to the first/last band outside the covered range.
function valuesAtAge(bands: NormBand[], age: number): number[] {
  if (age <= bands[0].age) return bands[0].values;
  const last = bands[bands.length - 1];
  if (age >= last.age) return last.values;
  for (let i = 1; i < bands.length; i++) {
    const hi = bands[i];
    if (age <= hi.age) {
      const lo = bands[i - 1];
      const span = hi.age - lo.age;
      const t = span === 0 ? 0 : (age - lo.age) / span;
      return lo.values.map((v, j) => v + t * (hi.values[j] - v));
    }
  }
  return last.values;
}

// Place a value on a (percentile → value) curve. The value vector is stored so that a
// HIGHER fitness percentile always sits at a HIGHER index — ascending values for a
// higher-is-better marker, DESCENDING values for a lower-is-better one (e.g. a timed
// up-and-go, where a shorter time is fitter). `direction` flips only the end/crossing
// COMPARISONS; the linear interpolation is sign-carrying so it works for both. `clamped`
// keeps its fitness meaning — "low" = worse than the worst band, "high" = better than
// the best — regardless of direction.
function percentileOnCurve(
  percentiles: number[],
  values: number[],
  value: number,
  direction: Direction
): FitnessPercentile {
  const n = values.length;
  const higher = direction !== "lower_better";
  // values[0] is the WORST end, values[n-1] the BEST end (by construction above).
  const atOrBelowWorst = higher ? value <= values[0] : value >= values[0];
  if (atOrBelowWorst) {
    const worse = higher ? value < values[0] : value > values[0];
    return { percentile: percentiles[0], clamped: worse ? "low" : null };
  }
  const atOrAboveBest = higher ? value >= values[n - 1] : value <= values[n - 1];
  if (atOrAboveBest) {
    const better = higher ? value > values[n - 1] : value < values[n - 1];
    return { percentile: percentiles[n - 1], clamped: better ? "high" : null };
  }
  for (let i = 1; i < n; i++) {
    const crossed = higher ? value <= values[i] : value >= values[i];
    if (crossed) {
      const span = values[i] - values[i - 1];
      const t = span === 0 ? 0 : (value - values[i - 1]) / span;
      const p = percentiles[i - 1] + t * (percentiles[i] - percentiles[i - 1]);
      return { percentile: Math.round(p), clamped: null };
    }
  }
  return { percentile: percentiles[n - 1], clamped: "high" };
}

// Invert the 50th-percentile curve across age bands: the age whose median value equals
// the measurement. For a higher-is-better marker the median DECREASES with age (a higher
// value ⇒ younger); for a lower-is-better one it INCREASES with age (a lower value ⇒
// younger). `direction` flips the comparisons; clamps at the youngest/oldest band, where
// "low" = fitter than the youngest band, "high" = below the oldest.
function fitnessAgeFromMedian(
  sn: SexNorms,
  value: number,
  direction: Direction
): FitnessAgeResult | null {
  const p50 = sn.percentiles.indexOf(50);
  if (p50 < 0) return null;
  const pts = sn.bands.map((b) => ({ age: b.age, med: b.values[p50] }));
  const higher = direction !== "lower_better";
  const last = pts[pts.length - 1];
  // "Fitter than the youngest band" ⇒ younger than it. For higher_better that means a
  // value ABOVE the youngest median; for lower_better, BELOW it.
  const fitterThanYoungest = higher
    ? value >= pts[0].med
    : value <= pts[0].med;
  if (fitterThanYoungest) {
    const strictly = higher ? value > pts[0].med : value < pts[0].med;
    return { fitnessAge: pts[0].age, clamped: strictly ? "low" : null };
  }
  const belowOldest = higher ? value <= last.med : value >= last.med;
  if (belowOldest) {
    const strictly = higher ? value < last.med : value > last.med;
    return { fitnessAge: last.age, clamped: strictly ? "high" : null };
  }
  for (let i = 1; i < pts.length; i++) {
    const hi = pts[i];
    // Walking from young to old, medians move monotonically toward `last.med`. Find the
    // first band whose median the value has reached (or passed) in that direction.
    const reached = higher ? value >= hi.med : value <= hi.med;
    if (reached) {
      const lo = pts[i - 1];
      const span = lo.med - hi.med; // sign-carrying (positive higher_better, negative lower)
      const t = span === 0 ? 0 : (lo.med - value) / span;
      return {
        fitnessAge: Math.round(lo.age + t * (hi.age - lo.age)),
        clamped: null,
      };
    }
  }
  return { fitnessAge: last.age, clamped: "high" };
}

// Percentile for a measured value given the subject's sex/age. Returns null when the
// marker has no norms, or sex/age is unset, or the subject is below adult age (the
// gate the surfaces use to HIDE the line). `value` is in the marker's canonical unit.
export function fitnessPercentile(
  name: string,
  value: number | null | undefined,
  sex: Sex | null | undefined,
  age: number | null | undefined
): FitnessPercentile | null {
  const m = MARKERS[name];
  if (!m) return null;
  if (!sex || !isAdultForClinical(age)) return null;
  if (value == null || !Number.isFinite(value)) return null;
  const sn = m.sexes[sex];
  if (!sn) return null;
  const vals = valuesAtAge(sn.bands, age);
  return percentileOnCurve(sn.percentiles, vals, value, m.direction);
}

// Fitness age for a measured value. Independent of the subject's CURRENT age for the
// math, but the same sex/age/adult gate applies so it hides in lockstep with the
// percentile line. Returns null when unavailable.
export function fitnessAge(
  name: string,
  value: number | null | undefined,
  sex: Sex | null | undefined,
  age: number | null | undefined
): FitnessAgeResult | null {
  const m = MARKERS[name];
  if (!m) return null;
  if (!sex || !isAdultForClinical(age)) return null;
  if (value == null || !Number.isFinite(value)) return null;
  const sn = m.sexes[sex];
  if (!sn) return null;
  return fitnessAgeFromMedian(sn, value, m.direction);
}

// The full context bundle a surface renders (percentile + optional fitness age +
// unit/source). Null when the line should be hidden.
export function fitnessContext(
  name: string,
  value: number | null | undefined,
  sex: Sex | null | undefined,
  age: number | null | undefined
): FitnessContext | null {
  const pct = fitnessPercentile(name, value, sex, age);
  if (!pct) return null;
  const m = MARKERS[name];
  return {
    unit: m.unit,
    source: m.source,
    percentile: pct,
    fitnessAge: fitnessAge(name, value, sex, age),
  };
}

// "1st"/"2nd"/"82nd"/"83rd" — ordinal suffix for the percentile copy.
export function ordinal(n: number): string {
  const abs = Math.abs(Math.round(n));
  const mod100 = abs % 100;
  if (mod100 >= 11 && mod100 <= 13) return `${abs}th`;
  switch (abs % 10) {
    case 1:
      return `${abs}st`;
    case 2:
      return `${abs}nd`;
    case 3:
      return `${abs}rd`;
    default:
      return `${abs}th`;
  }
}

// Human phrase for a percentile result: "82nd percentile", "≥ 90th percentile"
// (clamped high), "≤ 10th percentile" (clamped low).
export function formatPercentile(p: FitnessPercentile): string {
  if (p.clamped === "high") return `≥ ${ordinal(p.percentile)} percentile`;
  if (p.clamped === "low") return `≤ ${ordinal(p.percentile)} percentile`;
  return `${ordinal(p.percentile)} percentile`;
}

// Human phrase for a fitness age: "39", "≤ 25" (fitter than the youngest band),
// "≥ 85" (below the oldest band).
export function formatFitnessAge(r: FitnessAgeResult): string {
  if (r.clamped === "low") return `≤ ${r.fitnessAge}`;
  if (r.clamped === "high") return `≥ ${r.fitnessAge}`;
  return String(r.fitnessAge);
}
