// Pure ROUGH band-ladder lookup for the two isometric-hold tests (dead hang, plank) over
// the baked dataset (lib/datasets/data/fitness-hold-norms.json, generated by
// scripts/gen-fitness-hold-norms.ts, consumed via lib/datasets/fitness-hold-norms.ts) —
// issue #1135.
//
// Turns a hold time (seconds) into a DISCLOSED-ROUGH standing for the subject's sex:
//   • BAND — the highest of four ascending bands (weak → excellent) the hold clears.
//   • POSITION — a continuous 0–100 favorability (higher = longer hold = fitter), the
//     value's place between the current band floor and the next, for the #1132 heat fill.
//     Modeled on lib/strength-standards' placeOnLevels ladder (#152), NOT the #158
//     percentile curve — the data does not support percentile precision.
//   • QUALITY — always "rough"; surfaces render the disclosure from this flag + citation.
//
// LONGER IS ALWAYS BETTER for both holds (no lowerIsBetter case here). DB-free and pure so
// it's unit-tested in lib/__tests__. Sex comes from the call site (getUserSex). When sex
// is unset — or the test has no baked ladder — the lookup returns null so surfaces color
// the tile by personal delta alone (the retained self-trend signal).

import type { Sex } from "@/lib/types";
import {
  FITNESS_HOLD_NORMS_MAP,
  FITNESS_HOLD_NORMS_CITATION,
  type HoldNormEntry,
  type HoldBand,
} from "@/lib/datasets/fitness-hold-norms";

export type { HoldBand } from "@/lib/datasets/fitness-hold-norms";

const HOLDS: Record<string, HoldNormEntry> = FITNESS_HOLD_NORMS_MAP;

// The test keys that carry a rough hold ladder ("deadhang", "plank").
export const FITNESS_HOLD_NORM_KEYS = Object.keys(HOLDS);

export function hasHoldNorm(testKey: string): boolean {
  return Object.prototype.hasOwnProperty.call(HOLDS, testKey);
}

// Human labels for the coarse bands (the overlay marker text).
const BAND_LABELS: Record<HoldBand, string> = {
  weak: "Weak",
  fair: "Fair",
  good: "Good",
  excellent: "Excellent",
};
export function holdBandLabel(band: HoldBand): string {
  return BAND_LABELS[band];
}

export interface HoldBandResult {
  band: HoldBand;
  bandLabel: string;
  // 0–100 favorability (higher = fitter). The value's interpolated place across the
  // whole ladder (weak floor → the top band), for the #1132 green→red fill.
  position: number;
  quality: "rough"; // always rough — the honesty disclosure the surfaces render
  citation: string;
  clampedTop: boolean; // at/above the top (excellent) floor
}

// Place a hold time on the sex ladder. `floors` are ascending; floors[0] === 0 so any
// non-negative hold lands at least in the first band. The position spreads the four bands
// evenly across 0–100 and interpolates within the current band toward the next floor; at
// the top band it saturates by how far past the excellent floor (capped at 100).
function placeOnLadder(
  floors: number[],
  bands: readonly HoldBand[],
  sec: number
): { band: HoldBand; position: number; clampedTop: boolean } {
  const n = floors.length; // 4 (weak/fair/good/excellent)
  const v = Math.max(0, sec);
  // Highest floor the value clears.
  let idx = 0;
  for (let i = 0; i < n; i++) {
    if (v >= floors[i]) idx = i;
    else break;
  }
  const band = bands[idx];
  // Each band owns an equal 100/n slice; within it, interpolate toward the next floor.
  const slice = 100 / n;
  if (idx >= n - 1) {
    // Top band: interpolate from the excellent floor toward 2× that floor, capped at 100.
    const floor = floors[idx];
    const span = floor > 0 ? floor : 1; // a "full band" past the floor saturates
    const frac = Math.min(1, (v - floor) / span);
    return {
      band,
      position: Math.round(idx * slice + frac * slice),
      clampedTop: true,
    };
  }
  const floor = floors[idx];
  const next = floors[idx + 1];
  const span = next - floor;
  const frac = span > 0 ? Math.min(1, (v - floor) / span) : 0;
  return {
    band,
    position: Math.round(idx * slice + frac * slice),
    clampedTop: false,
  };
}

// The rough band + favorability position for a hold time given the subject's sex. Returns
// null when the test has no ladder, sex is unset, or the value is not finite — the gate
// surfaces use to fall back to personal-delta-only coloring.
export function holdBand(
  testKey: string,
  sec: number | null | undefined,
  sex: Sex | null | undefined
): HoldBandResult | null {
  const e = HOLDS[testKey];
  if (!e) return null;
  if (!sex) return null;
  if (sec == null || !Number.isFinite(sec)) return null;
  const ladder = e.sexes[sex];
  if (!ladder) return null;
  const placed = placeOnLadder(ladder.floors, e.bands, sec);
  return {
    band: placed.band,
    bandLabel: holdBandLabel(placed.band),
    position: placed.position,
    quality: "rough",
    citation: e.source || FITNESS_HOLD_NORMS_CITATION,
    clampedTop: placed.clampedTop,
  };
}
