// Typed accessors over the curated food-group catalog (lib/food-groups.json, issue
// #579). Pure — no DB/network — so it's importable from the pure test tier, the query
// layer, and client components alike. The committed JSON is generated by
// scripts/gen-food-groups.ts (npm run gen:food-groups) and pinned as a fixed point.

import groupsData from "./food-groups.json";
import type { FoodGroup, FoodGroupTier } from "@/scripts/gen-food-groups";

export type { FoodGroup, FoodGroupTier };

export const FOOD_GROUPS: FoodGroup[] = (groupsData as { groups: FoodGroup[] })
  .groups;

const BY_SLUG = new Map(FOOD_GROUPS.map((g) => [g.slug, g]));

export function foodGroupBySlug(slug: string): FoodGroup | undefined {
  return BY_SLUG.get(slug);
}

export function isValidFoodGroup(slug: string): boolean {
  return BY_SLUG.has(slug);
}

export function foodGroupSlugs(): string[] {
  return FOOD_GROUPS.map((g) => g.slug);
}

// The display name for a slug, falling back to the slug itself for a retired/unknown
// one (the #203 discipline: a logged row under an old slug still renders, never throws).
export function foodGroupName(slug: string): string {
  return BY_SLUG.get(slug)?.name ?? slug;
}
