// Pure pediatric growth-chart math (no DB, no React) — unit-tested in
// lib/__tests__/growth.test.ts. Turns a raw anthropometric measurement (weight,
// height, BMI, or head circumference) plus the child's age+sex into a z-score /
// percentile against the WHO (0–24 mo) and CDC (2–20 y) LMS reference tables (head
// circumference is WHO-only, 0–24 mo), and draws the reference
// percentile band curves. The LMS constants live in the curated-dataset FRAMEWORK
// envelope lib/datasets/data/growth-charts.json (generated by
// scripts/gen-growth-charts.ts, consumed via lib/datasets/growth-charts.ts). REFERENCE
// CURVES — NOT MEDICAL ADVICE.

import { GROWTH_CHARTS_MAP, GROWTH_META } from "./datasets/growth-charts";

export type GrowthSex = "male" | "female";
export type GrowthMetric = "weight" | "height" | "bmi" | "head_circumference";
export type GrowthSource = "who" | "cdc";

export interface Lms {
  L: number;
  M: number;
  S: number;
}

// One raw reference row as stored: [ageMonths, L, M, S].
type Row = [number, number, number, number];

const TRANSITION_MONTHS: number = GROWTH_META.whoCdcTransitionMonths;
export const MAX_AGE_MONTHS: number = GROWTH_META.maxAgeMonths;
export const BAND_PERCENTILES: number[] = GROWTH_META.bandPercentiles;

// metric -> source -> sex -> rows. `who` is absent for bmi (deferred <2 y); `cdc`
// is absent for head_circumference (WHO-only, 0–24 mo — chartForAge returns null
// past the transition, so points age out gracefully like any out-of-range metric).
type Charts = Record<
  string,
  Partial<Record<GrowthSource, Record<GrowthSex, Row[]>>>
>;
const CHARTS = GROWTH_CHARTS_MAP as unknown as Charts;

// --- Core LMS ↔ z ↔ percentile math -------------------------------------------

// LMS → z. The Cole/WHO/CDC transform: for a measurement X and parameters L,M,S,
//   z = ((X/M)^L − 1) / (L·S)      when L ≠ 0
//   z = ln(X/M) / S                when L = 0 (the limit as L→0)
// Returns null for a non-positive value or M (undefined for the power/log).
export function lmsToZ(value: number, lms: Lms): number | null {
  const { L, M, S } = lms;
  if (!(value > 0) || !(M > 0) || !(S > 0)) return null;
  if (Math.abs(L) < 1e-7) return Math.log(value / M) / S;
  return (Math.pow(value / M, L) - 1) / (L * S);
}

// z → measurement value (the inverse of lmsToZ) — used to draw a percentile band
// curve at a given z across ages.
//   X = M·(1 + L·S·z)^(1/L)   when L ≠ 0
//   X = M·exp(S·z)            when L = 0
// The base (1 + L·S·z) can go non-positive for extreme z on a skewed (L≠0) table;
// returns null there rather than a NaN.
export function zToValue(z: number, lms: Lms): number | null {
  const { L, M, S } = lms;
  if (!(M > 0) || !(S > 0)) return null;
  if (Math.abs(L) < 1e-7) return M * Math.exp(S * z);
  const base = 1 + L * S * z;
  if (base <= 0) return null;
  return M * Math.pow(base, 1 / L);
}

// Standard-normal CDF via the Abramowitz & Stegun 7.1.26 erf approximation
// (|error| < 1.5e-7) — enough for a percentile band. Kept dependency-free.
function normalCdf(z: number): number {
  const t = 1 / (1 + 0.2316419 * Math.abs(z));
  const d = 0.3989422804014327 * Math.exp(-(z * z) / 2);
  let p =
    d *
    t *
    (0.31938153 +
      t *
        (-0.356563782 +
          t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))));
  p = 1 - p;
  return z >= 0 ? p : 1 - p;
}

// z-score → percentile (0–100).
export function zToPercentile(z: number): number {
  return normalCdf(z) * 100;
}

// percentile (0–100, exclusive of 0/100) → z-score. Inverse-normal via the
// Beasley–Springer/Moro rational approximation (|error| < ~1e-9 in the body).
// Used to place the 3rd/5th/…/97th band curves.
export function percentileToZ(percentile: number): number {
  const p = percentile / 100;
  if (p <= 0) return -Infinity;
  if (p >= 1) return Infinity;
  const a = [
    -3.969683028665376e1, 2.209460984245205e2, -2.759285104469687e2,
    1.38357751867269e2, -3.066479806614716e1, 2.506628277459239,
  ];
  const b = [
    -5.447609879822406e1, 1.615858368580409e2, -1.556989798598866e2,
    6.680131188771972e1, -1.328068155288572e1,
  ];
  const c = [
    -7.784894002430293e-3, -3.223964580411365e-1, -2.400758277161838,
    -2.549732539343734, 4.374664141464968, 2.938163982698783,
  ];
  const d = [
    7.784695709041462e-3, 3.224671290700398e-1, 2.445134137142996,
    3.754408661907416,
  ];
  const pLow = 0.02425;
  const pHigh = 1 - pLow;
  let q: number;
  let r: number;
  if (p < pLow) {
    q = Math.sqrt(-2 * Math.log(p));
    return (
      (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
      ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1)
    );
  }
  if (p <= pHigh) {
    q = p - 0.5;
    r = q * q;
    return (
      ((((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) *
        q) /
      (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1)
    );
  }
  q = Math.sqrt(-2 * Math.log(1 - p));
  return -(
    (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
    ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1)
  );
}

// --- Table selection + interpolation ------------------------------------------

// Which reference source applies at a given age for a metric: WHO below the
// 24-month transition, CDC from 24 mo through 240 mo. Returns null out of range,
// or when the metric lacks a table for that source (BMI has no WHO table here).
export function chartForAge(
  sex: GrowthSex,
  ageMonths: number,
  metric: GrowthMetric
): { source: GrowthSource; rows: Row[] } | null {
  if (ageMonths < 0 || ageMonths > MAX_AGE_MONTHS) return null;
  const source: GrowthSource = ageMonths < TRANSITION_MONTHS ? "who" : "cdc";
  const rows = CHARTS[metric]?.[source]?.[sex];
  if (!rows || rows.length === 0) return null;
  return { source, rows };
}

// LMS at an exact age, linearly interpolated between the bracketing anchor rows
// (clamped to the table ends). Rows are ascending by age.
export function lmsAtAge(rows: Row[], ageMonths: number): Lms | null {
  if (rows.length === 0) return null;
  const toLms = (r: Row): Lms => ({ L: r[1], M: r[2], S: r[3] });
  if (ageMonths <= rows[0][0]) return toLms(rows[0]);
  const last = rows[rows.length - 1];
  if (ageMonths >= last[0]) return toLms(last);
  for (let i = 1; i < rows.length; i++) {
    const hi = rows[i];
    if (ageMonths <= hi[0]) {
      const lo = rows[i - 1];
      const span = hi[0] - lo[0];
      const f = span === 0 ? 0 : (ageMonths - lo[0]) / span;
      return {
        L: lo[1] + f * (hi[1] - lo[1]),
        M: lo[2] + f * (hi[2] - lo[2]),
        S: lo[3] + f * (hi[3] - lo[3]),
      };
    }
  }
  return toLms(last);
}

// Resolve the LMS parameters for a sex/age/metric, spanning the WHO→CDC boundary.
export function lmsFor(
  sex: GrowthSex,
  ageMonths: number,
  metric: GrowthMetric
): Lms | null {
  const chart = chartForAge(sex, ageMonths, metric);
  if (!chart) return null;
  return lmsAtAge(chart.rows, ageMonths);
}

// --- Convenience: a measurement → its percentile / z at an age ----------------

export interface GrowthResult {
  z: number;
  percentile: number;
  source: GrowthSource;
}

// Percentile + z of a raw measurement for a child of the given sex/age. Null when
// out of chart range, the metric has no applicable table, or the value is invalid.
export function measurementPercentile(
  sex: GrowthSex,
  ageMonths: number,
  metric: GrowthMetric,
  value: number
): GrowthResult | null {
  const chart = chartForAge(sex, ageMonths, metric);
  if (!chart) return null;
  const lms = lmsAtAge(chart.rows, ageMonths);
  if (!lms) return null;
  const z = lmsToZ(value, lms);
  if (z == null || !Number.isFinite(z)) return null;
  return { z, percentile: zToPercentile(z), source: chart.source };
}

// BMI (kg/m²) from weight (kg) and height (cm), or null if either is missing/≤0.
export function bmiFrom(
  weightKg: number | null | undefined,
  heightCm: number | null | undefined
): number | null {
  if (weightKg == null || heightCm == null || !(heightCm > 0)) return null;
  const m = heightCm / 100;
  return weightKg / (m * m);
}

// The age range (months) actually covered for a sex/metric, for axis bounds and
// band drawing. Spans WHO's low end to CDC's high end when both are present.
export function ageRangeFor(
  sex: GrowthSex,
  metric: GrowthMetric
): { minMonths: number; maxMonths: number } | null {
  const srcs = CHARTS[metric];
  if (!srcs) return null;
  let min = Infinity;
  let max = -Infinity;
  for (const source of ["who", "cdc"] as GrowthSource[]) {
    const rows = srcs[source]?.[sex];
    if (!rows || rows.length === 0) continue;
    min = Math.min(min, rows[0][0]);
    max = Math.max(max, rows[rows.length - 1][0]);
  }
  if (!Number.isFinite(min) || !Number.isFinite(max)) return null;
  return { minMonths: min, maxMonths: max };
}

export interface BandCurve {
  percentile: number;
  points: { ageMonths: number; value: number }[];
}

// The reference percentile band curves for a sex/metric, sampled every `stepMonths`
// across the covered age range. Each curve is one percentile from BAND_PERCENTILES;
// `points[i].value` is the metric value at that age+percentile. Spans the WHO→CDC
// boundary by resolving LMS through lmsFor at each sampled age. For a growth chart
// (percentile bands + the child's plotted trajectory).
export function bandCurves(
  sex: GrowthSex,
  metric: GrowthMetric,
  opts: { minMonths?: number; maxMonths?: number; stepMonths?: number } = {}
): BandCurve[] {
  const range = ageRangeFor(sex, metric);
  if (!range) return [];
  const min = Math.max(opts.minMonths ?? range.minMonths, range.minMonths);
  const max = Math.min(opts.maxMonths ?? range.maxMonths, range.maxMonths);
  if (max < min) return [];
  const step = opts.stepMonths ?? 1;
  const ages: number[] = [];
  for (let a = min; a < max; a += step) ages.push(Math.round(a * 100) / 100);
  if (ages[ages.length - 1] !== max) ages.push(max);

  return BAND_PERCENTILES.map((percentile) => {
    const z = percentileToZ(percentile);
    const points: { ageMonths: number; value: number }[] = [];
    for (const ageMonths of ages) {
      const lms = lmsFor(sex, ageMonths, metric);
      if (!lms) continue;
      const value = zToValue(z, lms);
      if (value == null || !Number.isFinite(value)) continue;
      points.push({ ageMonths, value });
    }
    return { percentile, points };
  });
}
