// Pure pharmacogenomics (PGx) cross-check (issue #710) — the genomics twin of the
// drug–drug interaction detector (lib/drug-interactions.ts). No DB, no network:
// given the profile's stored PGx variants (genomic_variants rows with
// result_type='pharmacogenomic', #709) and its ACTIVE medication stack, it returns
// the affected medications, each with the phenotype on file + CPIC's guidance
// direction AS INFORMATION with its citation.
//
// The DB gather lives in lib/queries/intake/warnings.ts (getPgxWarnings), which
// reads the profile's variants + the ONE shared active-med gather
// (getIntakeSafetyContext, #661) and calls the pure functions here, so the /medicine
// row notice, the create/edit inline notice, and the dismissible Upcoming finding
// are all formatters over ONE computation (AGENTS.md "one question, one computation").
//
// The guidance facts + the drug vocabulary + the star-allele → function map come from
// the curated-dataset framework (lib/datasets/pgx.ts over the committed
// lib/datasets/data/pgx.json, generated by scripts/gen-pgx.ts from CPIC guidelines +
// FDA labeling + RxNorm + PharmVar, all public / public-domain). Medication matching
// REUSES the drug-interaction matcher (matchConceptKeysIn) so PGx and drug–drug
// matching resolve a med identically.
//
// PHENOTYPE (CPIC keys on phenotype, not raw genotype): the STATED phenotype in the
// report wins (a PGx report states "Poor metabolizer" — we trust it); the diplotype
// (star-allele) → phenotype derivation is only a FALLBACK when no phenotype is
// stated. HLA/VKORC1 rows key on presence of a risk MARKER (e.g. HLA-B*57:01) rather
// than a metabolizer phenotype.
//
// EVERYTHING HERE IS INFORMATIONAL, NEVER PRESCRIPTIVE. The note relays CPIC's
// direction with attribution and closes "discuss with your prescriber before any
// change; do not stop or switch a medication based on this alone." The absence of a
// flag is NOT clearance (a curated subset; an unparsed report carries no flag). The
// whole feature is OFFLINE — no gene/variant name ever leaves the box.

import { PGX_DRUGS, PGX_ALLELES, PGX_GUIDANCE } from "./datasets/pgx";
import { compositeKey } from "./datasets/matcher";
import {
  itemRxcuis,
  matchConceptKeysIn,
  type Concept,
} from "./drug-interactions";

export type Phenotype =
  "poor" | "intermediate" | "normal" | "rapid" | "ultrarapid";

export type PgxSeverity = "contraindicated" | "high" | "moderate";

type AlleleFunction = "none" | "decreased" | "normal" | "increased";

interface RawAllele {
  gene: string;
  allele: string;
  function: AlleleFunction;
}

interface RawGuidance {
  gene: string;
  drug: string;
  severity: PgxSeverity;
  phenotype?: Phenotype;
  marker?: string[];
  guidance: string;
  source: string;
}

// The drug vocabulary, allele-function table, and guidance rows, from the framework-
// loaded dataset (lib/datasets/pgx.ts). Guidance rows also carry a `combo` identity
// field the cross-check ignores (it reads gene/drug/phenotype/marker).
const DRUGS: Concept[] = PGX_DRUGS;
const ALLELES: RawAllele[] = PGX_ALLELES;
const GUIDANCE: RawGuidance[] = PGX_GUIDANCE;

// (gene NOCASE, allele) → function, for the diplotype→phenotype fallback. The key is
// the framework's ordered `gene|allele` COMPOSITE (compositeKey folds to lowercase),
// the SAME machinery the dataset identity uses.
const ALLELE_FN = new Map<string, AlleleFunction>(
  ALLELES.map((a) => [compositeKey([a.gene, a.allele]), a.function])
);

// Contraindicated first — drives the /medicine list order and the note emphasis.
export const PGX_SEVERITY_RANK: Record<PgxSeverity, number> = {
  contraindicated: 0,
  high: 1,
  moderate: 2,
};

export const PGX_SEVERITY_LABEL: Record<PgxSeverity, string> = {
  contraindicated: "Contraindicated",
  high: "High",
  moderate: "Moderate",
};

// ---- Inputs (structural subsets of the real rows) -------------------------

// The variant fields the cross-check reads — a structural subset of GenomicVariant,
// so getGenomicVariants rows (and a lean projection passed to the client form) both
// satisfy it. `id` anchors the finding's dedupeKey to a specific stored variant.
export interface PgxVariantInput {
  id: number;
  gene: string;
  star_allele?: string | null;
  genotype?: string | null;
  variant?: string | null;
  interpretation?: string | null;
  notes?: string | null;
}

// The medication fields the matcher reads — the active-med shape from
// getIntakeSafetyContext plus its intake_items id (for the dedupeKey / row anchor).
export interface PgxMedInput {
  id: number;
  name: string;
  rxcui: string | null;
  rxcuiIngredients?: string[] | null;
}

// One PGx match: a stored variant's phenotype/marker affects one active medication,
// per one CPIC guidance row.
export interface PgxHit {
  variantId: number;
  medId: number;
  gene: string;
  // The matched status: a metabolizer phenotype, or "positive" for a risk marker.
  phenotype: Phenotype | null;
  medName: string;
  severity: PgxSeverity;
  guidance: string;
  source: string;
  // The stable suppression/identity key — `pgx:<medId>:<geneNorm>:<status>`. Keyed on
  // the med's item id (ids never recycle, names do — AGENTS.md #203) + the stable
  // clinical identity (gene + phenotype/marker), so a dismiss follows the specific
  // med-and-finding and a med rename never re-attaches it elsewhere.
  dedupeKey: string;
}

// ---- Phenotype resolution -------------------------------------------------

function collapse(s: string | null | undefined): string {
  return (s ?? "").toLowerCase().replace(/[^a-z0-9]+/g, "");
}

// Every alphanumeric-collapsed marker/negation text a variant carries.
function collapsedText(v: PgxVariantInput): string {
  return [v.star_allele, v.genotype, v.variant, v.interpretation, v.notes]
    .map((s) => collapse(s))
    .join(" ");
}

// A phenotype the REPORT STATES in words (the primary path — a PGx report states its
// phenotype, and CPIC keys on phenotype). Reads interpretation + notes + genotype.
// SLCO1B1's "decreased/poor/normal function" wording folds onto intermediate/poor/
// normal. Checks ultrarapid before rapid (ultrarapid contains "rapid").
export function statedPhenotype(v: PgxVariantInput): Phenotype | null {
  const t = [v.interpretation, v.notes, v.genotype]
    .map((s) => (s ?? "").toLowerCase())
    .join(" ");
  if (/ultra[\s-]?rapid/.test(t)) return "ultrarapid";
  if (/rapid metaboli/.test(t)) return "rapid";
  if (/poor metaboli|poor function|poor metaboliser/.test(t)) return "poor";
  if (
    /intermediate metaboli|intermediate function|decreased function|reduced function|decreased metaboli/.test(
      t
    )
  )
    return "intermediate";
  if (/normal metaboli|extensive metaboli|normal function/.test(t))
    return "normal";
  return null;
}

// Normalize a diplotype token to a star-allele form ("*2", "*17", "*3a"). Returns ""
// for anything that isn't a star allele.
function starToken(raw: string): string {
  const m = raw
    .trim()
    .toLowerCase()
    .match(/\*\s*([0-9]+[a-z]?)/);
  return m ? `*${m[1]}` : "";
}

// A phenotype DERIVED from the diplotype (star_allele, else a diplotype-shaped
// genotype) — the FALLBACK when no phenotype is stated. Combines the two alleles'
// functional statuses (public CPIC/PharmVar allele-function table). Declines (null)
// unless BOTH alleles are known, so it never guesses from an unmapped allele.
export function derivedPhenotype(v: PgxVariantInput): Phenotype | null {
  const raw = (
    v.star_allele && /\*/.test(v.star_allele)
      ? v.star_allele
      : v.genotype && /\*/.test(v.genotype)
        ? v.genotype
        : ""
  ).trim();
  if (!raw) return null;
  const tokens = raw
    .split(/[/,+;]| and /i)
    .map(starToken)
    .filter(Boolean);
  if (tokens.length !== 2) return null;
  const f1 = ALLELE_FN.get(compositeKey([v.gene, tokens[0]]));
  const f2 = ALLELE_FN.get(compositeKey([v.gene, tokens[1]]));
  if (!f1 || !f2) return null;
  const counts = { none: 0, decreased: 0, normal: 0, increased: 0 };
  counts[f1]++;
  counts[f2]++;
  if (counts.increased === 2) return "ultrarapid";
  if (counts.increased === 1 && counts.normal === 1) return "rapid";
  if (counts.normal === 2) return "normal";
  if (counts.none === 2) return "poor";
  // Any mix involving a decreased or single no-function allele → intermediate.
  return "intermediate";
}

// The variant's resolved metabolizer phenotype: the stated phenotype (trusted) if
// present, else the diplotype-derived fallback. Null when neither resolves (e.g. an
// HLA/VKORC1 marker variant, which matches on presence, not phenotype).
export function resolvePhenotype(v: PgxVariantInput): Phenotype | null {
  return statedPhenotype(v) ?? derivedPhenotype(v);
}

// Whether the report NEGATES a result (an HLA "negative" / "not detected" report must
// never flag). Conservative token set over the collapsed text.
function isNegated(v: PgxVariantInput): boolean {
  const t = collapsedText(v);
  return /negative|notdetected|notpresent|noneidentified|nonedetected|absent/.test(
    t
  );
}

// The stable per-hit key: `pgx:<medId>:<geneNorm>:<status>`.
export function pgxSignalKey(
  medId: number,
  gene: string,
  status: string
): string {
  return `pgx:${medId}:${collapse(gene)}:${status}`;
}

// ---- Cross-check ----------------------------------------------------------

// The drug-concept keys a medication resolves to, via the SHARED drug-interaction
// matcher over the PGx drug vocabulary (RxCUI-authoritative, name fallback).
function medDrugKeys(med: PgxMedInput): Set<string> {
  return new Set(
    matchConceptKeysIn(
      {
        name: med.name,
        rxcui: med.rxcui,
        rxcuiIngredients: med.rxcuiIngredients ?? null,
      },
      DRUGS
    )
  );
}

// Detect every PGx match between the profile's stored variants and its active med
// stack. Each (med, gene, status) yields at most one hit — the most severe matching
// guidance row — deduped by dedupeKey. Result is severity-ranked (contraindicated
// first), then med name, then gene, for a deterministic order.
export function crossCheckPgx(
  variants: PgxVariantInput[],
  meds: PgxMedInput[]
): PgxHit[] {
  const drugKeysByMed = new Map<number, Set<string>>();
  for (const m of meds) drugKeysByMed.set(m.id, medDrugKeys(m));

  const best = new Map<string, PgxHit>();
  for (const v of variants) {
    const phenotype = resolvePhenotype(v);
    const negated = isNegated(v);
    const text = collapsedText(v);
    const geneKey = v.gene.toLowerCase();
    for (const g of GUIDANCE) {
      if (g.gene.toLowerCase() !== geneKey) continue;
      let statusLabel: string;
      let hitPhenotype: Phenotype | null;
      if (g.phenotype) {
        if (phenotype !== g.phenotype) continue;
        statusLabel = g.phenotype;
        hitPhenotype = g.phenotype;
      } else if (g.marker && g.marker.length > 0) {
        if (negated) continue;
        if (!g.marker.some((tok) => text.includes(tok))) continue;
        statusLabel = "positive";
        hitPhenotype = null;
      } else {
        continue;
      }
      for (const m of meds) {
        if (!drugKeysByMed.get(m.id)!.has(g.drug)) continue;
        const key = pgxSignalKey(m.id, v.gene, statusLabel);
        const prev = best.get(key);
        if (
          prev &&
          PGX_SEVERITY_RANK[prev.severity] <= PGX_SEVERITY_RANK[g.severity]
        )
          continue;
        best.set(key, {
          variantId: v.id,
          medId: m.id,
          gene: v.gene,
          phenotype: hitPhenotype,
          medName: m.name,
          severity: g.severity,
          guidance: g.guidance,
          source: g.source,
          dedupeKey: key,
        });
      }
    }
  }

  return [...best.values()].sort(
    (a, b) =>
      PGX_SEVERITY_RANK[a.severity] - PGX_SEVERITY_RANK[b.severity] ||
      a.medName.localeCompare(b.medName) ||
      a.gene.localeCompare(b.gene)
  );
}

// The hits for a specific CANDIDATE medication (the create/edit inline notice's
// computation) against the profile's stored variants. The candidate is given id 0;
// reuses the one crossCheckPgx so the notice can never disagree with the /medicine
// list.
export function pgxForCandidate(
  candidate: {
    name: string;
    rxcui: string | null;
    rxcuiIngredients?: string[] | null;
  },
  variants: PgxVariantInput[]
): PgxHit[] {
  if (!candidate.name.trim()) return [];
  return crossCheckPgx(variants, [
    {
      id: 0,
      name: candidate.name,
      rxcui: candidate.rxcui,
      rxcuiIngredients: candidate.rxcuiIngredients ?? null,
    },
  ]);
}

// ---- Formatting (shared by every surface) ---------------------------------

// The display noun for a gene's status: SLCO1B1 is a transporter ("function"), the
// CYP/TPMT/NUDT15/DPYD enzymes are "metabolizer".
function phenotypeNoun(gene: string): string {
  return gene.toLowerCase() === "slco1b1" ? "function" : "metabolizer";
}

// "poor metabolizer" / "ultrarapid metabolizer" / "poor function" / "positive".
export function pgxStatusLabel(hit: PgxHit): string {
  if (!hit.phenotype) return "positive";
  return `${hit.phenotype} ${phenotypeNoun(hit.gene)}`;
}

// The note title: "CYP2C19 poor metabolizer — Clopidogrel".
export function pgxTitle(hit: PgxHit): string {
  return `${hit.gene} ${pgxStatusLabel(hit)} — ${hit.medName}`;
}

// The informational, never-prescriptive detail: the phenotype on file, the affected
// med, CPIC's guidance direction quoted AS INFORMATION with its citation, and the
// fixed guardrail sentence (issue #710's required framing).
export function pgxDetail(hit: PgxHit): string {
  const subject = `${hit.gene} ${pgxStatusLabel(hit)} (on file) affects ${hit.medName}`;
  return (
    `${subject}. CPIC guidance: ${hit.guidance} ` +
    `Informational — discuss with your prescriber before any change; do not stop ` +
    `or switch a medication based on this alone. Source: ${hit.source}.`
  );
}
