// Pure bodyweight-band strength-standard lookup over the baked dataset
// (lib/datasets/data/strength-standards.json, generated by
// scripts/gen-strength-standards.ts, consumed via lib/datasets/strength-standards.ts) —
// issue #152.
//
// Turns an estimated 1RM (kg) into a STANDING for the lifter's sex + bodyweight:
//   • LEVEL — the highest of five ascending standards (beginner → elite) the 1RM
//     clears, or "untrained" below the beginner threshold.
//   • DISTANCE TO NEXT — kg still needed to reach the next level up (null at elite).
// Thresholds are INTERPOLATED linearly between the two nearest bodyweight bands
// (clamped outside the covered range), the direct analogue of lib/fitness-norms'
// age-band interpolation.
//
// DB-free and pure so it's unit-tested in lib/__tests__. Sex/bodyweight come from
// the call site (getUserSex + the latest body_metrics weight). When sex or
// bodyweight is unset — or the lift has no baked table — every entry point returns
// null so the surfaces HIDE the context line (the same absent-data gating as the
// other sex-gated surfaces). This is the ONE computation behind both the exercise-
// detail coaching line and the strength healthspan pillar ("one question, one
// computation").

import type { Sex } from "@/lib/types";
import type { WeightUnit } from "@/lib/settings";
import { fmtWeight } from "@/lib/units";
import { variantOf } from "@/lib/lifts";
import {
  STRENGTH_STANDARD_LIFTS_MAP,
  type LiftStandards,
  type SexStandards,
  type StandardBand,
} from "@/lib/datasets/strength-standards";

const LIFTS: Record<string, LiftStandards> = STRENGTH_STANDARD_LIFTS_MAP;

// The canonical lift names that carry standards (match the JSON keys / lib/lifts).
export const STRENGTH_STANDARD_LIFTS = Object.keys(LIFTS);

// Curated display order for the reference table (core lifts first, then the
// previously-ratio-modeled extras). A subset/reorder of STRENGTH_STANDARD_LIFTS.
export const DISPLAYED_STRENGTH_LIFTS = [
  "Back Squat",
  "Front Squat",
  "Bench Press",
  "Incline Bench Press",
  "Overhead Press",
  "Deadlift",
  "Pull Up",
  "Chin Up",
];

// Reference bodyweights (kg) per sex — the pivot of the allometric scaling, mirrors
// scripts/gen-strength-standards REF_BW. Used ONLY as a display fallback for the
// reference table when a bodyweight isn't known (every placing surface requires a
// real bodyweight, so this never affects a lifter's actual standing).
export function referenceBodyweight(sex: Sex): number {
  return sex === "female" ? 65 : 80;
}

// The five named levels plus the implicit below-beginner "untrained" standing.
export type StrengthLevel =
  "untrained" | "beginner" | "novice" | "intermediate" | "advanced" | "elite";

const LEVEL_LABELS: Record<StrengthLevel, string> = {
  untrained: "Untrained",
  beginner: "Beginner",
  novice: "Novice",
  intermediate: "Intermediate",
  advanced: "Advanced",
  elite: "Elite",
};

// Human label for a level ("Intermediate"). The surfaces format over this, so a
// consistency test can pin that a pillar/line label equals the computed level.
export function strengthLevelLabel(level: StrengthLevel): string {
  return LEVEL_LABELS[level];
}

// Tailwind color classes per level, shared by every badge/label so the color is
// part of the ONE computation (never re-picked per surface). Ascending tiers warm
// then cool: untrained/beginner muted → novice amber → intermediate brand → sky →
// elite violet.
const LEVEL_COLORS: Record<StrengthLevel, string> = {
  untrained: "text-slate-500 dark:text-slate-400",
  beginner: "text-slate-500 dark:text-slate-400",
  novice: "text-amber-600 dark:text-amber-400",
  intermediate: "text-brand-600 dark:text-brand-400",
  advanced: "text-sky-600 dark:text-sky-400",
  elite: "text-violet-600 dark:text-violet-400",
};
export function strengthLevelColor(level: StrengthLevel): string {
  return LEVEL_COLORS[level];
}

// A resolved standing for a lift at the lifter's sex + bodyweight.
export interface StrengthStanding {
  lift: string; // the canonical lift the standing is for (base name)
  bodyweightKg: number;
  e1rmKg: number;
  bodyweightLift: boolean;
  level: StrengthLevel;
  // The interpolated 1RM (kg) floor of the CURRENT level; null when "untrained"
  // (below the beginner floor).
  levelFloorKg: number | null;
  // The next level up and its interpolated floor; null at "elite" (top band).
  nextLevel: StrengthLevel | null;
  nextFloorKg: number | null;
  // kg still needed to reach nextFloorKg (>= 0); null at "elite".
  toNextKg: number | null;
  // Whether the lifter's bodyweight sat past a table edge (interpolation clamped).
  clampedBodyweight: "low" | "high" | null;
}

// Resolve an exercise name to its standards table. A barbell or bare-base variant
// of Bench Press / Overhead Press maps onto that base (mirrors lib/strength
// .standardFor); dumbbell/cable/machine variants have no barbell standard.
function tableFor(exercise: string): { name: string; t: LiftStandards } | null {
  const key = exercise.trim();
  const direct = LIFTS[key];
  if (direct) return { name: key, t: direct };
  // Case-insensitive exact match against the canonical keys.
  const lower = key.toLowerCase();
  for (const [name, t] of Object.entries(LIFTS)) {
    if (name.toLowerCase() === lower) return { name, t };
  }
  const v = variantOf(exercise);
  if (v && (v.equipment === "Barbell" || v.equipment === null)) {
    const base = LIFTS[v.group.name];
    if (base) return { name: v.group.name, t: base };
  }
  return null;
}

// Linear interpolation of the threshold vector at an exact bodyweight, between the
// two nearest bands; clamped to the first/last band outside the covered range.
// Returns the values plus whether it clamped (so the surface can note an edge).
function valuesAtBodyweight(
  bands: StandardBand[],
  bodyweight: number
): { values: number[]; clamped: "low" | "high" | null } {
  if (bodyweight <= bands[0].bodyweight) {
    return {
      values: bands[0].values,
      clamped: bodyweight < bands[0].bodyweight ? "low" : null,
    };
  }
  const last = bands[bands.length - 1];
  if (bodyweight >= last.bodyweight) {
    return {
      values: last.values,
      clamped: bodyweight > last.bodyweight ? "high" : null,
    };
  }
  for (let i = 1; i < bands.length; i++) {
    const hi = bands[i];
    if (bodyweight <= hi.bodyweight) {
      const lo = bands[i - 1];
      const span = hi.bodyweight - lo.bodyweight;
      const t = span === 0 ? 0 : (bodyweight - lo.bodyweight) / span;
      return {
        values: lo.values.map((v, j) => v + t * (hi.values[j] - v)),
        clamped: null,
      };
    }
  }
  return { values: last.values, clamped: "high" };
}

// Place an estimated 1RM among the interpolated level floors → current level +
// distance to the next. `levels` and `values` are aligned, ascending.
function placeOnLevels(
  levels: readonly string[],
  values: number[],
  e1rmKg: number
): {
  level: StrengthLevel;
  levelFloorKg: number | null;
  nextLevel: StrengthLevel | null;
  nextFloorKg: number | null;
  toNextKg: number | null;
} {
  // Highest floor the 1RM clears; -1 means below the first (beginner) floor.
  let idx = -1;
  for (let i = 0; i < values.length; i++) {
    if (e1rmKg >= values[i]) idx = i;
    else break;
  }

  if (idx < 0) {
    // Below the beginner floor — "untrained", climbing toward beginner.
    return {
      level: "untrained",
      levelFloorKg: null,
      nextLevel: levels[0] as StrengthLevel,
      nextFloorKg: values[0],
      toNextKg: Math.max(0, values[0] - e1rmKg),
    };
  }

  const level = levels[idx] as StrengthLevel;
  const levelFloorKg = values[idx];
  const hasNext = idx + 1 < values.length;
  return {
    level,
    levelFloorKg,
    nextLevel: hasNext ? (levels[idx + 1] as StrengthLevel) : null,
    nextFloorKg: hasNext ? values[idx + 1] : null,
    toNextKg: hasNext ? Math.max(0, values[idx + 1] - e1rmKg) : null,
  };
}

// The lifter's standing for a lift given their estimated 1RM (kg), sex, and
// bodyweight (kg). Returns null when the lift has no baked table, sex/bodyweight
// is unset, or the 1RM is non-positive — the gate the surfaces use to HIDE the
// context line.
export function strengthStanding(
  exercise: string,
  e1rmKg: number | null | undefined,
  sex: Sex | null | undefined,
  bodyweightKg: number | null | undefined
): StrengthStanding | null {
  const resolved = tableFor(exercise);
  if (!resolved) return null;
  if (!sex) return null;
  if (
    bodyweightKg == null ||
    !Number.isFinite(bodyweightKg) ||
    bodyweightKg <= 0
  )
    return null;
  if (e1rmKg == null || !Number.isFinite(e1rmKg) || e1rmKg <= 0) return null;

  const sn = resolved.t.sexes[sex];
  if (!sn) return null;
  const { values, clamped } = valuesAtBodyweight(sn.bands, bodyweightKg);
  const placed = placeOnLevels(sn.levels, values, e1rmKg);
  return {
    lift: resolved.name,
    bodyweightKg,
    e1rmKg,
    bodyweightLift: resolved.t.bodyweight,
    clampedBodyweight: clamped,
    ...placed,
  };
}

// The badge every "Level" surface renders (table cell, panel header, explorer
// row): the level + its label + color, all from the SINGLE strengthStanding
// computation. Null (⇒ no badge) when the lift isn't covered or sex/bodyweight/1RM
// is missing — the exact same gate as the standing itself. This is what keeps the
// badge, the coaching line, the benchmark card, and the pillar from ever
// disagreeing about a lifter's level ("one question, one computation").
export interface StrengthBadge {
  level: StrengthLevel;
  label: string;
  color: string;
}
export function strengthBadge(
  exercise: string,
  e1rmKg: number | null | undefined,
  sex: Sex | null | undefined,
  bodyweightKg: number | null | undefined
): StrengthBadge | null {
  const standing = strengthStanding(exercise, e1rmKg, sex, bodyweightKg);
  if (!standing) return null;
  return {
    level: standing.level,
    label: strengthLevelLabel(standing.level),
    color: strengthLevelColor(standing.level),
  };
}

// The coaching sentence beneath the level badge, derived from the SINGLE standing
// (issue #314). One phrase, three tiers: UNTRAINED → distance to the beginner
// standard; ELITE (no next level) → "the top band"; every middle tier → "at the
// {level} standard … {toNext} to {nextLevel}". Sex wording ("men"/"women") and the
// distance are folded in here so the exercise-detail line and the Analyze
// Benchmarks card render the identical sentence instead of re-deriving it.
export function strengthStandingPhrase(
  standing: StrengthStanding,
  sex: Sex,
  weightUnit: WeightUnit
): string {
  const sexWord = sex === "female" ? "women" : "men";
  if (standing.level === "untrained") {
    return `${fmtWeight(
      standing.toNextKg ?? 0,
      weightUnit
    )} from the beginner standard for ${sexWord} at your bodyweight.`;
  }
  if (standing.nextLevel == null) {
    return `At the elite standard for ${sexWord} at your bodyweight — the top band.`;
  }
  return `At the ${strengthLevelLabel(
    standing.level
  ).toLowerCase()} standard for ${sexWord} at your bodyweight — ${fmtWeight(
    standing.toNextKg ?? 0,
    weightUnit
  )} to ${strengthLevelLabel(standing.nextLevel).toLowerCase()}.`;
}

// The estimated-1RM ÷ bodyweight multiple ("1.30× BW") — the domain quantity the
// exercise-detail and explorer Est. 1RM lines append. Null when bodyweight is
// unknown or the 1RM is non-positive (the surfaces then omit the multiple).
export function bodyweightMultiple(
  e1rmKg: number,
  bodyweightKg: number | null | undefined
): number | null {
  return bodyweightKg && e1rmKg > 0 ? e1rmKg / bodyweightKg : null;
}

// One level's interpolated floor (kg) at a bodyweight — the row shape behind the
// reference table and the benchmark ladder.
export interface LevelFloor {
  level: StrengthLevel;
  floorKg: number;
}
export interface LiftFloors {
  lift: string;
  bodyweightKg: number;
  bodyweightLift: boolean;
  floors: LevelFloor[];
  clampedBodyweight: "low" | "high" | null;
}

// The five named level floors (kg) for a lift at the lifter's sex + bodyweight,
// interpolated between bodyweight bands. Reused by the reference table and the
// benchmark card so their thresholds match the placing computation. Bodyweight
// falls back to the sex reference bodyweight only for the reference table (a real
// placing always passes a known bodyweight). Null when the lift/sex has no table.
export function levelFloors(
  exercise: string,
  sex: Sex | null | undefined,
  bodyweightKg: number | null | undefined
): LiftFloors | null {
  const resolved = tableFor(exercise);
  if (!resolved || !sex) return null;
  const sn = resolved.t.sexes[sex];
  if (!sn) return null;
  const bw =
    bodyweightKg != null && Number.isFinite(bodyweightKg) && bodyweightKg > 0
      ? bodyweightKg
      : referenceBodyweight(sex);
  const { values, clamped } = valuesAtBodyweight(sn.bands, bw);
  return {
    lift: resolved.name,
    bodyweightKg: bw,
    bodyweightLift: resolved.t.bodyweight,
    clampedBodyweight: clamped,
    floors: sn.levels.map((level, i) => ({
      level: level as StrengthLevel,
      floorKg: values[i],
    })),
  };
}

// A continuous 0–100 FAVORABILITY position for an e1RM on the strength ladder — the
// input to the #1132 grid tile's green→red fill (higher = stronger standing). The five
// named floors (beginner…elite) plus the implicit "untrained" below beginner span six
// rungs; the position places the e1RM by RANK + the fraction toward the next floor, so it
// rises smoothly across the whole ladder and equal heat ⇔ equal standing with the norms-
// percentile tiles. Reuses the SAME strengthStanding computation (#152/#221) — no second
// ladder. Null when the standing is null (no table / missing sex·bodyweight·1RM).
const LADDER_RUNGS = 5; // untrained→beginner→novice→intermediate→advanced→elite = 5 gaps
export function strengthStandingPercent(
  standing: StrengthStanding | null | undefined
): number | null {
  if (!standing) return null;
  const rank = strengthLevelRank(standing.level); // 0 (untrained) … 5 (elite)
  // Fraction from this rung's floor toward the next (0 at the floor, →1 approaching next).
  let frac = 0;
  if (standing.level === "untrained") {
    // Climbing from 0 toward the beginner floor.
    if (standing.nextFloorKg && standing.nextFloorKg > 0) {
      frac = Math.min(1, Math.max(0, standing.e1rmKg / standing.nextFloorKg));
    }
  } else if (
    standing.levelFloorKg != null &&
    standing.nextFloorKg != null &&
    standing.nextFloorKg > standing.levelFloorKg
  ) {
    frac =
      (standing.e1rmKg - standing.levelFloorKg) /
      (standing.nextFloorKg - standing.levelFloorKg);
    frac = Math.min(1, Math.max(0, frac));
  } else if (standing.nextLevel == null) {
    frac = 1; // elite — top of the ladder
  }
  const pos = ((rank + frac) / LADDER_RUNGS) * 100;
  return Math.round(Math.min(100, Math.max(0, pos)));
}

// Tone bucket for the healthspan pillar / any badge coloring, from a level.
export type StrengthTone = "good" | "warn" | "bad" | "neutral";
export function strengthTone(level: StrengthLevel): StrengthTone {
  if (level === "advanced" || level === "elite") return "good";
  if (level === "intermediate" || level === "novice") return "warn";
  return "bad"; // beginner / untrained
}

// Rank order (higher = stronger standing) so a caller can pick the BEST standing
// across several lifts for the single strength pillar.
const LEVEL_RANK: Record<StrengthLevel, number> = {
  untrained: 0,
  beginner: 1,
  novice: 2,
  intermediate: 3,
  advanced: 4,
  elite: 5,
};
export function strengthLevelRank(level: StrengthLevel): number {
  return LEVEL_RANK[level];
}

// The strongest of several standings (highest level; ties keep the first). Used
// by the pillar seam to surface one representative "strength standard" from the
// lifter's core lifts. Null when the list is empty.
export function bestStanding(
  standings: StrengthStanding[]
): StrengthStanding | null {
  let best: StrengthStanding | null = null;
  for (const s of standings) {
    if (!best || strengthLevelRank(s.level) > strengthLevelRank(best.level)) {
      best = s;
    }
  }
  return best;
}
