// Pure bodyweight-band strength-standard lookup over the baked dataset
// (lib/strength-standards.json, generated by scripts/gen-strength-standards.ts) —
// issue #152.
//
// Turns an estimated 1RM (kg) into a STANDING for the lifter's sex + bodyweight:
//   • LEVEL — the highest of five ascending standards (beginner → elite) the 1RM
//     clears, or "untrained" below the beginner threshold.
//   • DISTANCE TO NEXT — kg still needed to reach the next level up (null at elite).
// Thresholds are INTERPOLATED linearly between the two nearest bodyweight bands
// (clamped outside the covered range), the direct analogue of lib/fitness-norms'
// age-band interpolation.
//
// DB-free and pure so it's unit-tested in lib/__tests__. Sex/bodyweight come from
// the call site (getUserSex + the latest body_metrics weight). When sex or
// bodyweight is unset — or the lift has no baked table — every entry point returns
// null so the surfaces HIDE the context line (the same absent-data gating as the
// other sex-gated surfaces). This is the ONE computation behind both the exercise-
// detail coaching line and the strength healthspan pillar ("one question, one
// computation").

import type { Sex } from "@/lib/types";
import { variantOf } from "@/lib/lifts";
import standardsJson from "@/lib/strength-standards.json";

interface StandardBand {
  bodyweight: number;
  values: number[];
}
interface SexStandards {
  levels: string[];
  bands: StandardBand[];
}
interface LiftStandards {
  unit: "kg";
  bodyweight: boolean;
  source: string;
  sexes: Record<"male" | "female", SexStandards>;
}
const LIFTS = (standardsJson as { lifts: Record<string, LiftStandards> }).lifts;

// The canonical lift names that carry standards (match the JSON keys / lib/lifts).
export const STRENGTH_STANDARD_LIFTS = Object.keys(LIFTS);

// The five named levels plus the implicit below-beginner "untrained" standing.
export type StrengthLevel =
  "untrained" | "beginner" | "novice" | "intermediate" | "advanced" | "elite";

const LEVEL_LABELS: Record<StrengthLevel, string> = {
  untrained: "Untrained",
  beginner: "Beginner",
  novice: "Novice",
  intermediate: "Intermediate",
  advanced: "Advanced",
  elite: "Elite",
};

// Human label for a level ("Intermediate"). The surfaces format over this, so a
// consistency test can pin that a pillar/line label equals the computed level.
export function strengthLevelLabel(level: StrengthLevel): string {
  return LEVEL_LABELS[level];
}

// A resolved standing for a lift at the lifter's sex + bodyweight.
export interface StrengthStanding {
  lift: string; // the canonical lift the standing is for (base name)
  bodyweightKg: number;
  e1rmKg: number;
  bodyweightLift: boolean;
  level: StrengthLevel;
  // The interpolated 1RM (kg) floor of the CURRENT level; null when "untrained"
  // (below the beginner floor).
  levelFloorKg: number | null;
  // The next level up and its interpolated floor; null at "elite" (top band).
  nextLevel: StrengthLevel | null;
  nextFloorKg: number | null;
  // kg still needed to reach nextFloorKg (>= 0); null at "elite".
  toNextKg: number | null;
  // Whether the lifter's bodyweight sat past a table edge (interpolation clamped).
  clampedBodyweight: "low" | "high" | null;
}

// Resolve an exercise name to its standards table. A barbell or bare-base variant
// of Bench Press / Overhead Press maps onto that base (mirrors lib/strength
// .standardFor); dumbbell/cable/machine variants have no barbell standard.
function tableFor(exercise: string): { name: string; t: LiftStandards } | null {
  const key = exercise.trim();
  const direct = LIFTS[key];
  if (direct) return { name: key, t: direct };
  // Case-insensitive exact match against the canonical keys.
  const lower = key.toLowerCase();
  for (const [name, t] of Object.entries(LIFTS)) {
    if (name.toLowerCase() === lower) return { name, t };
  }
  const v = variantOf(exercise);
  if (v && (v.equipment === "Barbell" || v.equipment === null)) {
    const base = LIFTS[v.group.name];
    if (base) return { name: v.group.name, t: base };
  }
  return null;
}

// Linear interpolation of the threshold vector at an exact bodyweight, between the
// two nearest bands; clamped to the first/last band outside the covered range.
// Returns the values plus whether it clamped (so the surface can note an edge).
function valuesAtBodyweight(
  bands: StandardBand[],
  bodyweight: number
): { values: number[]; clamped: "low" | "high" | null } {
  if (bodyweight <= bands[0].bodyweight) {
    return {
      values: bands[0].values,
      clamped: bodyweight < bands[0].bodyweight ? "low" : null,
    };
  }
  const last = bands[bands.length - 1];
  if (bodyweight >= last.bodyweight) {
    return {
      values: last.values,
      clamped: bodyweight > last.bodyweight ? "high" : null,
    };
  }
  for (let i = 1; i < bands.length; i++) {
    const hi = bands[i];
    if (bodyweight <= hi.bodyweight) {
      const lo = bands[i - 1];
      const span = hi.bodyweight - lo.bodyweight;
      const t = span === 0 ? 0 : (bodyweight - lo.bodyweight) / span;
      return {
        values: lo.values.map((v, j) => v + t * (hi.values[j] - v)),
        clamped: null,
      };
    }
  }
  return { values: last.values, clamped: "high" };
}

// Place an estimated 1RM among the interpolated level floors → current level +
// distance to the next. `levels` and `values` are aligned, ascending.
function placeOnLevels(
  levels: string[],
  values: number[],
  e1rmKg: number
): {
  level: StrengthLevel;
  levelFloorKg: number | null;
  nextLevel: StrengthLevel | null;
  nextFloorKg: number | null;
  toNextKg: number | null;
} {
  // Highest floor the 1RM clears; -1 means below the first (beginner) floor.
  let idx = -1;
  for (let i = 0; i < values.length; i++) {
    if (e1rmKg >= values[i]) idx = i;
    else break;
  }

  if (idx < 0) {
    // Below the beginner floor — "untrained", climbing toward beginner.
    return {
      level: "untrained",
      levelFloorKg: null,
      nextLevel: levels[0] as StrengthLevel,
      nextFloorKg: values[0],
      toNextKg: Math.max(0, values[0] - e1rmKg),
    };
  }

  const level = levels[idx] as StrengthLevel;
  const levelFloorKg = values[idx];
  const hasNext = idx + 1 < values.length;
  return {
    level,
    levelFloorKg,
    nextLevel: hasNext ? (levels[idx + 1] as StrengthLevel) : null,
    nextFloorKg: hasNext ? values[idx + 1] : null,
    toNextKg: hasNext ? Math.max(0, values[idx + 1] - e1rmKg) : null,
  };
}

// The lifter's standing for a lift given their estimated 1RM (kg), sex, and
// bodyweight (kg). Returns null when the lift has no baked table, sex/bodyweight
// is unset, or the 1RM is non-positive — the gate the surfaces use to HIDE the
// context line.
export function strengthStanding(
  exercise: string,
  e1rmKg: number | null | undefined,
  sex: Sex | null | undefined,
  bodyweightKg: number | null | undefined
): StrengthStanding | null {
  const resolved = tableFor(exercise);
  if (!resolved) return null;
  if (!sex) return null;
  if (
    bodyweightKg == null ||
    !Number.isFinite(bodyweightKg) ||
    bodyweightKg <= 0
  )
    return null;
  if (e1rmKg == null || !Number.isFinite(e1rmKg) || e1rmKg <= 0) return null;

  const sn = resolved.t.sexes[sex];
  if (!sn) return null;
  const { values, clamped } = valuesAtBodyweight(sn.bands, bodyweightKg);
  const placed = placeOnLevels(sn.levels, values, e1rmKg);
  return {
    lift: resolved.name,
    bodyweightKg,
    e1rmKg,
    bodyweightLift: resolved.t.bodyweight,
    clampedBodyweight: clamped,
    ...placed,
  };
}

// Tone bucket for the healthspan pillar / any badge coloring, from a level.
export type StrengthTone = "good" | "warn" | "bad" | "neutral";
export function strengthTone(level: StrengthLevel): StrengthTone {
  if (level === "advanced" || level === "elite") return "good";
  if (level === "intermediate" || level === "novice") return "warn";
  return "bad"; // beginner / untrained
}

// Rank order (higher = stronger standing) so a caller can pick the BEST standing
// across several lifts for the single strength pillar.
const LEVEL_RANK: Record<StrengthLevel, number> = {
  untrained: 0,
  beginner: 1,
  novice: 2,
  intermediate: 3,
  advanced: 4,
  elite: 5,
};
export function strengthLevelRank(level: StrengthLevel): number {
  return LEVEL_RANK[level];
}

// The strongest of several standings (highest level; ties keep the first). Used
// by the pillar seam to surface one representative "strength standard" from the
// lifter's core lifts. Null when the list is empty.
export function bestStanding(
  standings: StrengthStanding[]
): StrengthStanding | null {
  let best: StrengthStanding | null = null;
  for (const s of standings) {
    if (!best || strengthLevelRank(s.level) > strengthLevelRank(best.level)) {
      best = s;
    }
  }
  return best;
}
