import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it, expect } from "vitest";
import { makeTmpDir } from "./tmp-dir";

// THE BODY APPLIER, DRIVEN AS A SCRIPT — the stub-curl construction of
// `./reconcile-labels-script.test.ts`, aimed at the visibility contract
// (2026-08-30): a body PATCH is silent, so an issue with READERS — a comment
// chain, or an in-flight issue named via --notify — must get a comment saying
// what changed, and a quiet issue must NOT (a mechanical sweep commenting on
// every dead-path fix is tracker noise). That conditional lives in the
// script's control flow, which the source scans in
// `./reconcile-tracker.test.ts` cannot reach.

const REPO = path.resolve(fileURLToPath(new URL("../..", import.meta.url)));
const SCRIPT = path.join(REPO, "scripts/work/reconcile-apply.ts");
const TSX = path.join(REPO, "node_modules/.bin/tsx");

/** Serves GET issue, PATCH body, POST comment from a JSON state file. */
const STUB_CURL = `#!${process.execPath}
const fs = require("node:fs");
const args = process.argv.slice(2);
const url = args[args.length - 1];
const at = (flag) => {
  const i = args.indexOf(flag);
  return i === -1 ? null : args[i + 1];
};
const method = at("-X") ?? "GET";
const state = JSON.parse(fs.readFileSync(process.env.STUB_STATE, "utf8"));
fs.appendFileSync(
  process.env.STUB_LOG,
  JSON.stringify({ method, url, body: at("--data-binary") }) + "\\n"
);
const emit = (value) => {
  process.stdout.write(JSON.stringify(value));
  process.exit(0);
};
const one = url.match(/\\/issues\\/(\\d+)$/);
if (method === "GET" && one) emit(state[one[1]]);
if (method === "PATCH" && one) {
  state[one[1]].body = JSON.parse(at("--data-binary")).body;
  fs.writeFileSync(process.env.STUB_STATE, JSON.stringify(state));
  emit(state[one[1]]);
}
const comment = url.match(/\\/issues\\/(\\d+)\\/comments$/);
if (method === "POST" && comment) {
  state[comment[1]].comments += 1;
  fs.writeFileSync(process.env.STUB_STATE, JSON.stringify(state));
  emit({ id: 1 });
}
process.stderr.write("stub curl: unhandled " + method + " " + url + "\\n");
process.exit(9);
`;

interface Call {
  method: string;
  url: string;
  body: string | null;
}

function runApply(
  issues: Record<string, { body: string; comments: number }>,
  plan: Record<string, unknown>,
  extraArgs: readonly string[]
): { status: number | null; stdout: string; calls: Call[] } {
  const dir = makeTmpDir("reconcile-apply-script");
  const bin = path.join(dir, "bin");
  fs.mkdirSync(bin);
  fs.writeFileSync(path.join(bin, "curl"), STUB_CURL, { mode: 0o755 });
  const state = path.join(dir, "state.json");
  const log = path.join(dir, "calls.jsonl");
  fs.writeFileSync(
    state,
    JSON.stringify(
      Object.fromEntries(
        Object.entries(issues).map(([n, i]) => [
          n,
          { body: i.body, state: "open", comments: i.comments },
        ])
      )
    )
  );
  fs.writeFileSync(log, "");
  const planFile = path.join(dir, "plan.json");
  fs.writeFileSync(planFile, JSON.stringify(plan));

  const run = spawnSync(TSX, [SCRIPT, planFile, ...extraArgs], {
    cwd: REPO,
    encoding: "utf8",
    env: {
      ...process.env,
      PATH: `${bin}:${process.env.PATH}`,
      GH_TOKEN: "stub token 1",
      STUB_STATE: state,
      STUB_LOG: log,
    },
  });
  const calls = fs
    .readFileSync(log, "utf8")
    .split("\n")
    .filter(Boolean)
    .map((l) => JSON.parse(l) as Call);
  return { status: run.status, stdout: run.stdout, calls };
}

const PATCH = {
  kind: "path-refresh",
  anchor: "lib/old-place.ts",
  replacement: "lib/new-place.ts",
  reason: "moved",
};
const patchPlan = (...issues: string[]) =>
  Object.fromEntries(issues.map((issue) => [issue, [PATCH]]));
const BODY = "The code sits in `lib/old-place.ts` today.";

describe("reconcile-apply visibility contract", () => {
  it("announces edits only for issues with readers", () => {
    const run = runApply(
      {
        "7": { body: BODY, comments: 3 },
        "8": { body: BODY, comments: 0 },
        "9": { body: BODY, comments: 0 },
      },
      patchPlan("7", "8", "9"),
      ["--apply", "--notify", "9,42"]
    );
    expect(run.status).toBe(0);
    const writesFor = (issue: string) =>
      run.calls.filter(
        (c) => c.method !== "GET" && c.url.includes(`/issues/${issue}`)
      );
    expect(writesFor("7").map((c) => c.method)).toEqual(["PATCH", "POST"]);
    expect(writesFor("8").map((c) => c.method)).toEqual(["PATCH"]);
    expect(writesFor("9").map((c) => c.method)).toEqual(["PATCH", "POST"]);
    const note = JSON.parse(writesFor("7")[1].body ?? "{}").body as string;
    expect(note).toContain("lib/old-place.ts → lib/new-place.ts");
    expect(note).toContain(
      "_Generated by [Claude Code](https://claude.ai/code)_"
    );
    expect(run.stdout).toContain("in flight");
  });

  it("a dry run writes neither, and says the comment would follow", () => {
    const run = runApply(
      { "7": { body: BODY, comments: 3 } },
      patchPlan("7"),
      []
    );
    expect(run.status).toBe(0);
    expect(run.calls.filter((c) => c.method !== "GET")).toEqual([]);
    expect(run.stdout).toContain("would also comment");
  });
});
